RDFlib GeoSPARQL: geosparql.geosparql_aggregates Namespace Reference
geosparql.geosparql_aggregates Namespace Reference
Classes
class AggBoundingBox
class AggBoundingCircle
class AggCentroid
class AggCollect
class AggConcaveHull
class AggConvexHull
class AggUnion
Functions
processLiteralTypeToGeom (literal)
Function Documentation
processLiteralTypeToGeom()
processLiteralTypeToGeom (literal)
def processLiteralTypeToGeom(literal):
    if not isinstance(literal,Literal):
        raise ValueError(
            "The "+str(literal)+" is not a literal!"
        )
    dtype=str(literal.datatype)
    if dtype=="http://www.opengis.net/ont/geosparql#wktLiteral":
        lstring=str(literal).strip()
        if lstring.startswith("<"):
            srsuri=lstring[0:lstring.find(">")].replace("<","").replace(">","")
            return shapely.from_wkt(lstring[lstring.find(">")+1:])
        else:
            return shapely.from_wkt(str(literal))
    elif dtype == "http://www.opengis.net/ont/geosparql#wkbLiteral":
        return shapely.from_wkb(str(literal))
    elif dtype == "http://www.opengis.net/ont/geosparql#geoJSONLiteral":
        return shapely.from_geojson(str(literal))
    elif dtype == "http://www.opengis.net/ont/geosparql#kmlLiteral":
        return kml.KML.from_string(str(literal))
    else:
        thelit=str(literal)
        if len(thelit)>100:
            thelit=thelit[0:100]
        raise ValueError(
            "The literal "+thelit+" ("+str(literal.datatype)+") is no known geometry literal type!"
        )
Referenced by AggBoundingBox.update(), AggBoundingCircle.update(), AggCentroid.update(), AggCollect.update(), AggConcaveHull.update(), AggConvexHull.update(), and AggUnion.update().