SPARQLing Unicorn Ontology Documentation: geosparql.geosparql Namespace Reference
geosparql.geosparql Namespace Reference
Classes
class LiteralUtils
class SRSUtils
class Transformers
Functions
merge_dicts (*dict_args)
Literal area (a)
Literal azimuth (a)
Literal asDGGS (a, dggsType)
Literal asGeoJSON (a)
Literal asGLTF (a)
Literal asGeocode (a, geocodeURI)
Literal asGML (a)
Literal asKML (a)
Literal asOBJ (a)
Literal asPLY (a)
Literal asXYZ (a)
Literal asWKB (a)
Literal asWKT (a)
Literal boundary (a)
Literal boundingCircle (a)
Literal buffer (a, radius, unit)
Literal centroid (a)
Literal contains (a, b)
Literal concaveHull (a)
Literal convexHull (a)
Literal coordinateDimension (a)
Literal compactnessRatio (a)
Literal covers (a, b)
Literal coveredBy (a, b)
Literal|None|Any crosses (a, b)
Literal disjoint (a, b)
Literal difference (a, b)
Literal distance (a, b)
Literal endPoint (a)
Literal equals (a, b)
Literal envelope (a)
Literal extrude (a, extrudeval)
Literal exteriorRing (a)
Literal flipXY (a)
Literal force2D (a)
Literal frechetDistance (a, b)
Literal geometryN (a, n)
Literal geometryType (a)
Literal getSRID (a)
Literal hausDorffDistance (a, b)
Literal inside (a, b)
Literal intersection (a, b)
Literal intersection3D (a, b)
Literal intersects (a, b)
Literal intersects3D (a, b)
Literal is3D (a)
Literal isCollection (a)
Literal isClosed (a)
Literal isEmpty (a)
Literal isMeasured (a)
Literal isRing (a)
Literal isSimple (a)
Literal isValid (a)
Literal length (a)
Literal m (a)
Literal matrixTransform (a, matrix)
Literal maxM (a)
Literal maxX (a)
Literal maxY (a)
Literal maxZ (a)
Literal metricArea (a)
Literal metricBuffer (a, radius)
Literal metricDistance (a, b)
Literal metricLength (a)
Literal metricPerimeter (a)
Literal metricWithinDistance (a, b, d)
Literal minimumBoundingRadius (a)
Literal minimumClearance (a)
Literal minimumClearanceLine (a)
Literal minM (a)
Literal minX (a)
Literal minY (a)
Literal minZ (a)
Literal numGeometries (a)
Literal numInteriorRing (a)
Literal numPatches (a)
Literal numPoints (a)
Literal patchN (a, n)
Literal pointN (a, n)
Literal pointOnSurface (a)
Literal perimeter (a)
Literal overlaps (a, b)
Literal relate (a, b, matrix)
Literal reverse (a)
Literal scale (a, scaleX, scaleY, scaleZ)
Literal shortestLine (a, b)
Literal simplify (a, tolerance)
Literal skew (a, xs, ys)
Literal spatialDimension (a)
Literal startPoint (a)
Literal symDifference (a, b)
Literal transform (a, srsIRI)
Literal transformCRS84 (a)
Literal translate (a, deltaX, deltaY, deltaZ)
Literal touches (a, b)
Literal union (a, b)
Literal within (a, b)
Literal withinDistance (a, b, d)
Literal x (a)
Literal y (a)
Literal z (a)
getfuncs ()
Variables
str GEOF = "http://www.opengis.net/def/function/geosparql/"
str GEOFEXT = "http://www.opengis.net/def/function/geosparql/ext/"
str GEOFPREFIX = "geof:"
str GEOFEXTPREFIX = "geofext:"
str GEO = "http://www.opengis.net/ont/geosparql#"
str CRS84URI = "http://www.opengis.net/def/crs/OGC/1.3/CRS84"
dict geosparql10
dict geosparql11
dict geosparql13
g = Graph()
dir_path = os.path.dirname(os.path.realpath(__file__))
result
Function Documentation
area()
Literal area (a)
def area(a) -> Literal:
    thegeom, thegeomsrs = LiteralUtils.processLiteralTypeToGeom(a)
    return Literal(shapely.area(thegeom), datatype=XSD.double)
asDGGS()
Literal asDGGS (a, dggsType)
def asDGGS(a, dggsType) -> Literal:
    thegeom, thegeomsrs = LiteralUtils.processLiteralTypeToGeom(a)
    #print(a)
    #print(dggsType)
    #print(Transformers.transformToDGGS(thegeom, dggsType))
    return Literal(Transformers.transformToDGGS(thegeom, dggsType),datatype="http://www.opengis.net/ont/geosparql#dggsLiteral")
asGeocode()
Literal asGeocode (a, geocodeURI)
def asGeocode(a, geocodeURI) -> Literal:
    thegeom, thegeomsrs = LiteralUtils.processLiteralTypeToGeom(a)
    print(thegeom)
    print(geocodeURI)
    return Literal(Transformers.transformToGeocode(thegeom, str(geocodeURI)),
                   datatype="http://www.opengis.net/ont/geosparql#geocodeLiteral")
asGeoJSON()
Literal asGeoJSON (a)
def asGeoJSON(a) -> Literal:
    thegeom, thegeomsrs = LiteralUtils.processLiteralTypeToGeom(a)
    return LiteralUtils.processGeomToLiteral(thegeom, "http://www.opengis.net/ont/geosparql#geoJSONLiteral", thegeomsrs)
asGLTF()
Literal asGLTF (a)
def asGLTF(a) -> Literal:
    thegeom, thegeomsrs = LiteralUtils.processLiteralTypeToGeom(a, create3D=True)
    return LiteralUtils.processGeomToLiteral(thegeom, "http://www.opengis.net/ont/geosparql#gltfLiteral", thegeomsrs)
asGML()
Literal asGML (a)
def asGML(a) -> Literal:
    thegeom, thegeomsrs = LiteralUtils.processLiteralTypeToGeom(a)
    return LiteralUtils.processGeomToLiteral(thegeom, "http://www.opengis.net/ont/geosparql#gmlLiteral", thegeomsrs)
asKML()
Literal asKML (a)
def asKML(a) -> Literal:
    thegeom, thegeomsrs = LiteralUtils.processLiteralTypeToGeom(a)
    return LiteralUtils.processGeomToLiteral(thegeom, "http://www.opengis.net/ont/geosparql#kmlLiteral", thegeomsrs)
asOBJ()
Literal asOBJ (a)
def asOBJ(a) -> Literal:
    thegeom, thegeomsrs = LiteralUtils.processLiteralTypeToGeom(a, create3D=True)
    return LiteralUtils.processGeomToLiteral(thegeom, "http://www.opengis.net/ont/geosparql#objLiteral", thegeomsrs)
asPLY()
Literal asPLY (a)
def asPLY(a) -> Literal:
    thegeom, thegeomsrs = LiteralUtils.processLiteralTypeToGeom(a, create3D=True)
    return LiteralUtils.processGeomToLiteral(thegeom, "http://www.opengis.net/ont/geosparql#plyLiteral", thegeomsrs)
asWKB()
Literal asWKB (a)
def asWKB(a) -> Literal:
    thegeom, thegeomsrs = LiteralUtils.processLiteralTypeToGeom(a)
    return LiteralUtils.processGeomToLiteral(thegeom, "http://www.opengis.net/ont/geosparql#wkbLiteral", thegeomsrs)
asWKT()
Literal asWKT (a)
def asWKT(a) -> Literal:
    thegeom, thegeomsrs = LiteralUtils.processLiteralTypeToGeom(a)
    return LiteralUtils.processGeomToLiteral(thegeom, "http://www.opengis.net/ont/geosparql#wktLiteral", thegeomsrs)
asXYZ()
Literal asXYZ (a)
def asXYZ(a) -> Literal:
    thegeom, thegeomsrs = LiteralUtils.processLiteralTypeToGeom(a, create3D=True)
    return LiteralUtils.processGeomToLiteral(thegeom, "http://www.opengis.net/ont/geosparql#xyzLiteral", thegeomsrs)
azimuth()
Literal azimuth (a)
def azimuth(a) -> Literal:
    thegeom, thegeomsrs = LiteralUtils.processLiteralTypeToGeom(a)
    minrect = thegeom.minimum_rotated_rectangle
    minrectb = minrect.boundary
    coords = [c for c in minrectb.coords]  # List the line coordinates
    segments = [shapely.geometry.LineString([a, b]) for a, b in zip(coords, coords[1:])]  # Create the four side lines.
    longest_segment = max(segments, key=lambda x: x.length)
    p1, p2 = [c for c in longest_segment.coords]  # List the start and end coordinates of it
    azimuthangle = degrees(atan2(p2[1] - p1[1], p2[0] - p1[0]))
    return Literal(azimuthangle, datatype=XSD.double)
boundary()
Literal boundary (a)
def boundary(a) -> Literal:
    thegeom, thegeomsrs = LiteralUtils.processLiteralTypeToGeom(a)
    return LiteralUtils.processGeomToLiteral(shapely.boundary(thegeom), a.datatype, thegeomsrs)
boundingCircle()
Literal boundingCircle (a)
def boundingCircle(a) -> Literal:
    thegeom, thegeomsrs = LiteralUtils.processLiteralTypeToGeom(a)
    return LiteralUtils.processGeomToLiteral(shapely.minimum_bounding_circle(thegeom), a.datatype, thegeomsrs)
buffer()
Literal buffer (a, radius, unit)
def buffer(a, radius, unit) -> Literal:
    thegeom, thegeomsrs = LiteralUtils.processLiteralTypeToGeom(a)
    if isinstance(radius, Literal) and radius.datatype == XSD.double:
        return LiteralUtils.processGeomToLiteral(shapely.buffer(thegeom, float(radius)), a.datatype, thegeomsrs)
centroid()
Literal centroid (a)
def centroid(a) -> Literal:
    thegeom, thegeomsrs = LiteralUtils.processLiteralTypeToGeom(a)
    return LiteralUtils.processGeomToLiteral(thegeom.centroid, a.datatype, thegeomsrs)
compactnessRatio()
Literal compactnessRatio (a)
def compactnessRatio(a) -> Literal:
    thegeom, thegeomsrs = LiteralUtils.processLiteralTypeToGeom(a)
    p = thegeom.length
    a = thegeom.area
    return Literal(str(1 / (p / (2 * pi * sqrt(a / pi)))), datatype=XSD.double)
concaveHull()
Literal concaveHull (a)
def concaveHull(a) -> Literal:
    thegeom, thegeomsrs = LiteralUtils.processLiteralTypeToGeom(a)
    return LiteralUtils.processGeomToLiteral(shapely.concave_hull(thegeom), a.datatype, thegeomsrs)
contains()
Literal contains (a, b)
def contains(a, b) -> Literal:
    geoms = list(zip(*LiteralUtils.processLiteralsToGeom([a, b], normalize=True)))[0]
    if geoms[0] is not None and geoms[1] is not None:
        return Literal(shapely.contains(geoms[0], geoms[1]), datatype=XSD.boolean)
convexHull()
Literal convexHull (a)
def convexHull(a) -> Literal:
    thegeom, thegeomsrs = LiteralUtils.processLiteralTypeToGeom(a)
    return LiteralUtils.processGeomToLiteral(thegeom.convex_hull, a.datatype, thegeomsrs)
coordinateDimension()
Literal coordinateDimension (a)
def coordinateDimension(a) -> Literal:
    thegeom, thegeomsrs = LiteralUtils.processLiteralTypeToGeom(a)
    return Literal(shapely.get_coordinate_dimension(thegeom), datatype=XSD.integer)
coveredBy()
Literal coveredBy (a, b)
def coveredBy(a, b) -> Literal:
    geoms = list(zip(*LiteralUtils.processLiteralsToGeom([a, b], normalize=True)))[0]
    if geoms[0] is not None and geoms[1] is not None:
        return Literal(shapely.covered_by(geoms[0], geoms[1]), datatype=XSD.boolean)
covers()
Literal covers (a, b)
def covers(a, b) -> Literal:
    geoms = list(zip(*LiteralUtils.processLiteralsToGeom([a, b], normalize=True)))[0]
    if geoms[0] is not None and geoms[1] is not None:
        return Literal(shapely.covers(geoms[0], geoms[1]), datatype=XSD.boolean)
crosses()
Literal | None | Any crosses (a, b)
def crosses(a, b) -> Literal | None | Any:
    geoms = list(zip(*LiteralUtils.processLiteralsToGeom([a, b], normalize=True)))[0]
    if geoms[0] is not None and geoms[1] is not None:
        return Literal(shapely.crosses(geoms[0], geoms[1]), datatype=XSD.boolean)
difference()
Literal difference (a, b)
def difference(a, b) -> Literal:
    geomtps = LiteralUtils.processLiteralsToGeom([a, b], normalize=True)
    print(geomtps)
    print(shapely.difference(geomtps[0][0], geomtps[1][0]))
    if len(geomtps) > 1:
        return LiteralUtils.processGeomToLiteral(shapely.difference(geomtps[0][0], geomtps[1][0]), a.datatype,
                                                 geomtps[0][1])
disjoint()
Literal disjoint (a, b)
def disjoint(a, b) -> Literal:
    geoms = list(zip(*LiteralUtils.processLiteralsToGeom([a, b], normalize=True)))[0]
    print(geoms[0])
    print(geoms[1])
    if geoms[0] is not None and geoms[1] is not None:
        return Literal(shapely.disjoint(geoms[0], geoms[1]), datatype=XSD.boolean)
distance()
Literal distance (a, b)
def distance(a, b) -> Literal:
    geoms = list(zip(*LiteralUtils.processLiteralsToGeom([a, b], normalize=True)))[0]
    if geoms[0] is not None and geoms[1] is not None:
        return Literal(shapely.distance(geoms[0], geoms[1]), datatype=XSD.double)
endPoint()
Literal endPoint (a)
def endPoint(a) -> Literal:
    thegeom, thegeomsrs = LiteralUtils.processLiteralTypeToGeom(a)
    return LiteralUtils.processGeomToLiteral(shapely.Point(shapely.get_coordinates(thegeom)[-1]), a.datatype,
                                             thegeomsrs)
envelope()
Literal envelope (a)
def envelope(a) -> Literal:
    thegeom, thegeomsrs = LiteralUtils.processLiteralTypeToGeom(a)
    return LiteralUtils.processGeomToLiteral(thegeom.envelope, a.datatype, thegeomsrs)
equals()
Literal equals (a, b)
def equals(a, b) -> Literal:
    geoms = list(zip(*LiteralUtils.processLiteralsToGeom([a, b], normalize=True)))[0]
    if geoms[0] is not None and geoms[1] is not None:
        return Literal(shapely.equals(geoms[0], geoms[1]), datatype=XSD.boolean)
exteriorRing()
Literal exteriorRing (a)
def exteriorRing(a) -> Literal:
    thegeom, thegeomsrs = LiteralUtils.processLiteralTypeToGeom(a)
    return LiteralUtils.processGeomToLiteral(shapely.get_exterior_ring(thegeom), a.datatype, thegeomsrs)
extrude()
Literal extrude (a, extrudeval)
def extrude(a, extrudeval) -> Literal:
    thegeom, thegeomsrs = LiteralUtils.processLiteralTypeToGeom(a)
    return LiteralUtils.processGeomToLiteral(shapely.force_3d(shapely.force_2d(thegeom), extrudeval), a.datatype,
                                             thegeomsrs)
flipXY()
Literal flipXY (a)
def flipXY(a) -> Literal:
    thegeom, thegeomsrs = LiteralUtils.processLiteralTypeToGeom(a)
    return LiteralUtils.processGeomToLiteral(shapely.ops.transform(lambda x, y: (y, x),thegeom), a.datatype, thegeomsrs)
force2D()
Literal force2D (a)
def force2D(a) -> Literal:
    thegeom, thegeomsrs = LiteralUtils.processLiteralTypeToGeom(a)
    return LiteralUtils.processGeomToLiteral(shapely.force_2d(thegeom), a.datatype, thegeomsrs)
frechetDistance()
Literal frechetDistance (a, b)
def frechetDistance(a, b) -> Literal:
    geoms = list(zip(*LiteralUtils.processLiteralsToGeom([a, b], normalize=True)))[0]
    if geoms[0] is not None and geoms[1] is not None:
        return Literal(shapely.frechet_distance(geoms[0], geoms[1]), datatype=XSD.double)
geometryN()
Literal geometryN (a, n)
def geometryN(a, n) -> Literal:
    if isinstance(a, Literal) and isinstance(n, Literal) and n.datatype == XSD.integer:
        thegeom, thegeomsrs = LiteralUtils.processLiteralTypeToGeom(a)
        print(thegeom)
        print(shapely.get_geometry(thegeom, int(str(n))))
        return LiteralUtils.processGeomToLiteral(shapely.get_geometry(thegeom, int(str(n))), a.datatype, thegeomsrs)
geometryType()
Literal geometryType (a)
def geometryType(a) -> Literal:
    thegeom, thegeomsrs = LiteralUtils.processLiteralTypeToGeom(a)
    return Literal(thegeom.geom_type, datatype=XSD.string)
getfuncs()
getfuncs ()
def getfuncs():
    thefuncs = merge_dicts(geosparql10, geosparql11, geosparql13)
    for uri in thefuncs:
        try:
            register_custom_function(uri, thefuncs[uri])
            print("Registered custom function", uri)
            # print(thefuncs[uri])
        except ValueError:
            pass
        except AttributeError:
            pass
References geosparql.geosparql.getfuncs(), and geosparql.geosparql.merge_dicts().
Referenced by geosparql.geosparql.getfuncs().
getSRID()
Literal getSRID (a)
def getSRID(a) -> Literal:
    thegeom, thegeomsrs = LiteralUtils.processLiteralTypeToGeom(a)
    return Literal(thegeomsrs, datatype=XSD.anyURI)
hausDorffDistance()
Literal hausDorffDistance (a, b)
def hausDorffDistance(a, b) -> Literal:
    geoms = list(zip(*LiteralUtils.processLiteralsToGeom([a, b], normalize=True)))[0]
    if geoms[0] is not None and geoms[1] is not None:
        return Literal(shapely.hausdorff_distance(geoms[0], geoms[1]), datatype=XSD.double)
inside()
Literal inside (a, b)
def inside(a, b) -> Literal:
    geoms = list(zip(*LiteralUtils.processLiteralsToGeom([a, b], normalize=True)))[0]
    if geoms[0] is not None and geoms[1] is not None:
        print(shapely.contains_properly(geoms[1], geoms[0]))
        return Literal(shapely.contains_properly(geoms[1], geoms[0]), datatype=XSD.boolean)
intersection()
Literal intersection (a, b)
def intersection(a, b) -> Literal:
    geomtps = LiteralUtils.processLiteralsToGeom([a, b], normalize=True)
    if len(geomtps) > 1:
        return LiteralUtils.processGeomToLiteral(shapely.intersection(geomtps[0][0], geomtps[1][0]), a.datatype,
                                                 geomtps[0][1])
intersection3D()
Literal intersection3D (a, b)
def intersection3D(a, b) -> Literal:
    geoms = list(zip(*LiteralUtils.processLiteralsToGeom([a, b], normalize=True, create3D=True)))[0]
    if geoms[0] is not None and geoms[1] is not None:
        return Literal(trimesh.boolean.intersection(geoms), datatype=XSD.boolean)
intersects()
Literal intersects (a, b)
def intersects(a, b) -> Literal:
    geoms = list(zip(*LiteralUtils.processLiteralsToGeom([a, b], normalize=True)))[0]
    if geoms[0] is not None and geoms[1] is not None:
        return Literal(shapely.intersects(geoms[0], geoms[1]), datatype=XSD.boolean)
intersects3D()
Literal intersects3D (a, b)
def intersects3D(a, b) -> Literal:
    geoms = list(zip(*LiteralUtils.processLiteralsToGeom([a, b], normalize=True, create3D=True)))[0]
    if geoms[0] is not None and geoms[1] is not None:
        print(trimesh.boolean.boolean_manifold(geoms, "intersection"))
        return Literal(trimesh.boolean.boolean_manifold(geoms, "intersection"), datatype=XSD.boolean)
is3D()
Literal is3D (a)
def is3D(a) -> Literal:
    thegeom, thegeomsrs = LiteralUtils.processLiteralTypeToGeom(a)
    return Literal(thegeom.has_z, datatype=XSD.boolean)
isClosed()
Literal isClosed (a)
def isClosed(a) -> Literal:
    thegeom, thegeomsrs = LiteralUtils.processLiteralTypeToGeom(a)
    if "Polygon" in thegeom.geom_type:
        return Literal(True, datatype=XSD.boolean)
    return Literal(thegeom.is_closed, datatype=XSD.boolean)
isCollection()
Literal isCollection (a)
def isCollection(a) -> Literal:
    thegeom, thegeomsrs = LiteralUtils.processLiteralTypeToGeom(a)
    return Literal(str(thegeom.geom_type) == "GeometryCollection" or str(thegeom.geom_type).startswith("Multi"),
                   datatype=XSD.boolean)
isEmpty()
Literal isEmpty (a)
def isEmpty(a) -> Literal:
    thegeom, thegeomsrs = LiteralUtils.processLiteralTypeToGeom(a)
    print(thegeom)
    print(shapely.is_empty(thegeom))
    return Literal(shapely.is_empty(thegeom), datatype=XSD.boolean)
isMeasured()
Literal isMeasured (a)
def isMeasured(a) -> Literal:
    thegeom, thegeomsrs = LiteralUtils.processLiteralTypeToGeom(a)
    return Literal(thegeom.has_m, datatype=XSD.boolean)
isRing()
Literal isRing (a)
def isRing(a) -> Literal:
    thegeom, thegeomsrs = LiteralUtils.processLiteralTypeToGeom(a)
    if "Polygon" in str(thegeom.geom_type):
        return Literal(True, datatype=XSD.boolean)
    return Literal(thegeom.is_ring, datatype=XSD.boolean)
isSimple()
Literal isSimple (a)
def isSimple(a) -> Literal:
    thegeom, thegeomsrs = LiteralUtils.processLiteralTypeToGeom(a)
    print(thegeom.is_simple)
    print("The Lit: " + str(Literal(thegeom.is_simple, datatype=XSD.boolean)))
    return Literal(thegeom.is_simple, datatype=XSD.boolean)
isValid()
Literal isValid (a)
def isValid(a) -> Literal:
    thegeom, thegeomsrs = LiteralUtils.processLiteralTypeToGeom(a)
    return Literal(thegeom.is_valid, datatype=XSD.boolean)
length()
Literal length (a)
def length(a) -> Literal:
    thegeom, thegeomsrs = LiteralUtils.processLiteralTypeToGeom(a)
    return Literal(thegeom.length, datatype=XSD.double)
m()
Literal m (a)
def m(a) -> Literal:
    thegeom, thegeomsrs = LiteralUtils.processLiteralTypeToGeom(a)
    if thegeom.geom_type == "Point":
        return Literal(shapely.get_m(thegeom), datatype=XSD.double)
matrixTransform()
Literal matrixTransform (a, matrix)
def matrixTransform(a, matrix) -> Literal:
    thegeom, thegeomsrs = LiteralUtils.processLiteralTypeToGeom(a)
    shapely.affinity.affine_transform(thegeom, [])
    if thegeom.geom_type == "Point":
        return Literal(shapely.get_m(thegeom), datatype=XSD.double)
maxM()
Literal maxM (a)
def maxM(a) -> Literal:
    thegeom, thegeomsrs = LiteralUtils.processLiteralTypeToGeom(a)
    clist = shapely.get_coordinates(thegeom, include_m=True).tolist()
    flinf = -float("inf")
    maxM = flinf
    for c in clist:
        if c[2] != nan and maxM < c[2]:
            maxM = c[2]
    if maxM == flinf:
        maxM = "NaN"
    return Literal(str(maxM), datatype=XSD.double)
maxX()
Literal maxX (a)
def maxX(a) -> Literal:
    thegeom, thegeomsrs = LiteralUtils.processLiteralTypeToGeom(a)
    return Literal(shapely.total_bounds(thegeom)[2], datatype=XSD.double)
maxY()
Literal maxY (a)
def maxY(a) -> Literal:
    thegeom, thegeomsrs = LiteralUtils.processLiteralTypeToGeom(a)
    return Literal(shapely.total_bounds(thegeom)[3], datatype=XSD.double)
maxZ()
Literal maxZ (a)
def maxZ(a) -> Literal:
    thegeom, thegeomsrs = LiteralUtils.processLiteralTypeToGeom(a)
    clist = shapely.get_coordinates(thegeom, include_z=True).tolist()
    flinf = -float("inf")
    maxZ = flinf
    for c in clist:
        if c[2] != nan and maxZ < c[2]:
            maxZ = c[2]
    if maxZ == flinf:
        maxZ = "NaN"
    return Literal(str(maxZ), datatype=XSD.double)
merge_dicts()
merge_dicts (* dict_args)
Given any number of dictionaries, shallow copy and merge into a new dict,
precedence goes to key-value pairs in latter dictionaries.
def merge_dicts(*dict_args):
    """
    Given any number of dictionaries, shallow copy and merge into a new dict,
    precedence goes to key-value pairs in latter dictionaries.
    """
    result = {}
    for dictionary in dict_args:
        result.update(dictionary)
    return result
Referenced by geosparql.geosparql.getfuncs().
metricArea()
Literal metricArea (a)
def metricArea(a) -> Literal:
    thegeom, thegeomsrs = LiteralUtils.processLiteralTypeToGeom(a)
    normgeom = Transformers.transformToSRS(thegeom, thegeomsrs, 3857)
    return Literal(shapely.area(normgeom), datatype=XSD.double)
metricBuffer()
Literal metricBuffer (a, radius)
def metricBuffer(a, radius) -> Literal:
    thegeom, thegeomsrs = LiteralUtils.processLiteralTypeToGeom(a)
    normgeom = Transformers.transformToSRS(thegeom, thegeomsrs, 3857)
    if isinstance(radius, Literal) and radius.datatype == XSD.double:
        return LiteralUtils.processGeomToLiteral(shapely.buffer(normgeom, float(radius)), a.datatype, thegeomsrs)
metricDistance()
Literal metricDistance (a, b)
def metricDistance(a, b) -> Literal:
    geoms = list(zip(*LiteralUtils.processLiteralsToGeom([a, b], normalize=True, normsrs=3857)))[0]
    if geoms[0] is not None and geoms[1] is not None:
        return Literal(shapely.distance(geoms[0], geoms[1]), datatype=XSD.double)
metricLength()
Literal metricLength (a)
def metricLength(a) -> Literal:
    thegeom, thegeomsrs = LiteralUtils.processLiteralTypeToGeom(a)
    normgeom = Transformers.transformToSRS(thegeom, thegeomsrs, 3857)
    return Literal(shapely.length(normgeom), datatype=XSD.double)
metricPerimeter()
Literal metricPerimeter (a)
def metricPerimeter(a) -> Literal:
    thegeom, thegeomsrs = LiteralUtils.processLiteralTypeToGeom(a)
    normgeom = Transformers.transformToSRS(thegeom, thegeomsrs, 3857)
    return Literal(normgeom.length, datatype=XSD.double)
metricWithinDistance()
Literal metricWithinDistance (a, b, d)
def metricWithinDistance(a, b, d) -> Literal:
    geoms = list(zip(*LiteralUtils.processLiteralsToGeom([a, b], normalize=True, normsrs=3857)))[0]
    if isinstance(d, Literal) and d.datatype == XSD.double:
        distance = float(str(d))
        return Literal(shapely.dwithin(geoms[0], geoms[1], distance), datatype=XSD.boolean)
minimumBoundingRadius()
Literal minimumBoundingRadius (a)
def minimumBoundingRadius(a) -> Literal:
    thegeom, thegeomsrs = LiteralUtils.processLiteralTypeToGeom(a)
    return Literal(shapely.minimum_bounding_radius(thegeom), datatype=XSD.double)
minimumClearance()
Literal minimumClearance (a)
def minimumClearance(a) -> Literal:
    thegeom, thegeomsrs = LiteralUtils.processLiteralTypeToGeom(a)
    return Literal(shapely.minimum_clearance(thegeom), datatype=XSD.double)
minimumClearanceLine()
Literal minimumClearanceLine (a)
def minimumClearanceLine(a) -> Literal:
    thegeom, thegeomsrs = LiteralUtils.processLiteralTypeToGeom(a)
    # print(shapely.minimum_clearance_line(thegeom))
    return LiteralUtils.processGeomToLiteral(shapely.minimum_clearance_line(thegeom), a.datatype)
minM()
Literal minM (a)
def minM(a) -> Literal:
    thegeom, thegeomsrs = LiteralUtils.processLiteralTypeToGeom(a)
    clist = shapely.get_coordinates(thegeom, include_m=True).tolist()
    flinf = float("inf")
    minM = flinf
    for c in clist:
        if c[2] != nan and minM > c[2]:
            minM = c[2]
    if minM == flinf:
        minM = "NaN"
    return Literal(str(minM), datatype=XSD.double)
minX()
Literal minX (a)
def minX(a) -> Literal:
    thegeom, thegeomsrs = LiteralUtils.processLiteralTypeToGeom(a)
    return Literal(shapely.total_bounds(thegeom)[0], datatype=XSD.double)
minY()
Literal minY (a)
def minY(a) -> Literal:
    thegeom, thegeomsrs = LiteralUtils.processLiteralTypeToGeom(a)
    return Literal(shapely.total_bounds(thegeom)[1], datatype=XSD.double)
minZ()
Literal minZ (a)
def minZ(a) -> Literal:
    thegeom, thegeomsrs = LiteralUtils.processLiteralTypeToGeom(a)
    clist = shapely.get_coordinates(thegeom, include_z=True).tolist()
    flinf = float("inf")
    minZ = flinf
    for c in clist:
        print(c)
        if c[2] != nan and minZ > c[2]:
            minZ = c[2]
    if minZ == flinf:
        minZ = "NaN"
    return Literal(str(minZ), datatype=XSD.double)
numGeometries()
Literal numGeometries (a)
def numGeometries(a) -> Literal:
    thegeom, thegeomsrs = LiteralUtils.processLiteralTypeToGeom(a)
    return Literal(shapely.get_num_geometries(thegeom), datatype=XSD.integer)
numInteriorRing()
Literal numInteriorRing (a)
def numInteriorRing(a) -> Literal:
    thegeom, thegeomsrs = LiteralUtils.processLiteralTypeToGeom(a)
    return Literal(shapely.get_num_interior_rings(thegeom), datatype=XSD.integer)
numPatches()
Literal numPatches (a)
def numPatches(a) -> Literal:
    thegeom, thegeomsrs = LiteralUtils.processLiteralTypeToGeom(a)
    return Literal(len(shapely.get_parts(thegeom)), datatype=XSD.integer)
numPoints()
Literal numPoints (a)
def numPoints(a) -> Literal:
    thegeom, thegeomsrs = LiteralUtils.processLiteralTypeToGeom(a)
    return Literal(shapely.count_coordinates(thegeom), datatype=XSD.integer)
overlaps()
Literal overlaps (a, b)
def overlaps(a, b) -> Literal:
    geoms = list(zip(*LiteralUtils.processLiteralsToGeom([a, b], normalize=True)))[0]
    if geoms[0] is not None and geoms[1] is not None:
        return Literal(shapely.overlaps(geoms[0], geoms[1]), datatype=XSD.boolean)
patchN()
Literal patchN (a, n)
def patchN(a, n) -> Literal:
    thegeom, thegeomsrs = LiteralUtils.processLiteralTypeToGeom(a)
    return LiteralUtils.processGeomToLiteral(shapely.get_parts(thegeom).tolist()[n], a.datatype)
perimeter()
Literal perimeter (a)
def perimeter(a) -> Literal:
    thegeom, thegeomsrs = LiteralUtils.processLiteralTypeToGeom(a)
    return Literal(thegeom.length, datatype=XSD.double)
pointN()
Literal pointN (a, n)
def pointN(a, n) -> Literal:
    thegeom, thegeomsrs = LiteralUtils.processLiteralTypeToGeom(a)
    if "Polygon" in str(thegeom.geom_type):
        return LiteralUtils.processGeomToLiteral(shapely.get_point(shapely.get_exterior_ring(thegeom), int(str(n))), a.datatype, thegeomsrs)
    return LiteralUtils.processGeomToLiteral(shapely.get_point(thegeom, int(str(n))), a.datatype, thegeomsrs)
pointOnSurface()
Literal pointOnSurface (a)
def pointOnSurface(a) -> Literal:
    thegeom, thegeomsrs = LiteralUtils.processLiteralTypeToGeom(a)
    print(shapely.point_on_surface(thegeom))
    return LiteralUtils.processGeomToLiteral(shapely.point_on_surface(thegeom), a.datatype, thegeomsrs)
relate()
Literal relate (a, b, matrix)
def relate(a, b, matrix) -> Literal:
    geoms = list(zip(*LiteralUtils.processLiteralsToGeom([a, b], normalize=True)))[0]
    if geoms[0] is not None and geoms[1] is not None:
        return Literal(shapely.relate_pattern(geoms[0], geoms[1], str(matrix)), datatype=XSD.boolean)
reverse()
Literal reverse (a)
def reverse(a) -> Literal:
    thegeom, thegeomsrs = LiteralUtils.processLiteralTypeToGeom(a)
    return LiteralUtils.processGeomToLiteral(shapely.reverse(thegeom), a.datatype, thegeomsrs)
scale()
Literal scale (a, scaleX, scaleY, scaleZ)
def scale(a, scaleX, scaleY, scaleZ) -> Literal:
    thegeom, thegeomsrs = LiteralUtils.processLiteralTypeToGeom(a)
    print(shapely.affinity.scale(thegeom, xfact=float(scaleX.value), yfact=float(scaleY.value),
                                 zfact=float(scaleZ.value)))
    return LiteralUtils.processGeomToLiteral(
        shapely.affinity.scale(thegeom, xfact=float(scaleX.value), yfact=float(scaleY.value),
                               zfact=float(scaleZ.value)), a.datatype, thegeomsrs)
shortestLine()
Literal shortestLine (a, b)
def shortestLine(a, b) -> Literal:
    geomtps = LiteralUtils.processLiteralsToGeom([a, b], normalize=True)
    print(geomtps)
    print(geomtps[0][0])
    print(geomtps[1][0])
    print(shapely.shortest_line(geomtps[0][0], geomtps[1][0]))
    if len(geomtps) > 1:
        return LiteralUtils.processGeomToLiteral(shapely.shortest_line(geomtps[0][0], geomtps[1][0]), a.datatype,
                                                 geomtps[0][1])
simplify()
Literal simplify (a, tolerance)
def simplify(a, tolerance) -> Literal:
    thegeom, thegeomsrs = LiteralUtils.processLiteralTypeToGeom(a)
    return LiteralUtils.processGeomToLiteral(shapely.simplify(thegeom, float(tolerance)), a.datatype, thegeomsrs)
skew()
Literal skew (a, xs, ys)
def skew(a, xs, ys) -> Literal:
    thegeom, thegeomsrs = LiteralUtils.processLiteralTypeToGeom(a)
    return LiteralUtils.processGeomToLiteral(shapely.affinity.skew(thegeom, xs, ys), a.datatype, thegeomsrs)
spatialDimension()
Literal spatialDimension (a)
def spatialDimension(a) -> Literal:
    thegeom, thegeomsrs = LiteralUtils.processLiteralTypeToGeom(a)
    return Literal(shapely.get_dimensions(thegeom), datatype=XSD.integer)
startPoint()
Literal startPoint (a)
def startPoint(a) -> Literal:
    thegeom, thegeomsrs = LiteralUtils.processLiteralTypeToGeom(a)
    return LiteralUtils.processGeomToLiteral(shapely.Point(shapely.get_coordinates(thegeom)[0]), a.datatype, thegeomsrs)
symDifference()
Literal symDifference (a, b)
def symDifference(a, b) -> Literal:
    geomtps = LiteralUtils.processLiteralsToGeom([a, b], normalize=True)
    if len(geomtps) > 1:
        return LiteralUtils.processGeomToLiteral(shapely.symmetric_difference(geomtps[0][0], geomtps[1][0]), a.datatype,
                                                 geomtps[0][1])
touches()
Literal touches (a, b)
def touches(a, b) -> Literal:
    geoms = list(zip(*LiteralUtils.processLiteralsToGeom([a, b], normalize=True)))[0]
    if geoms[0] is not None and geoms[1] is not None:
        return Literal(shapely.touches(geoms[0], geoms[1]), datatype=XSD.boolean)
    raise ValueError("Invalid parameters were provided for function geof:touches")
transform()
Literal transform (a, srsIRI)
def transform(a, srsIRI) -> Literal:
    thegeom, thegeomsrs = LiteralUtils.processLiteralTypeToGeom(a)
    print("TRANSFORM FUNCTION")
    geom=Transformers.transformToSRS(thegeom, thegeomsrs, srsIRI)
    print("GEOM: "+str(geom))
    print("AS LITERAL: "+str(LiteralUtils.processGeomToLiteral(geom, a.datatype,srsIRI)))
    if thegeom is not None and thegeomsrs is not None:
        return LiteralUtils.processGeomToLiteral(Transformers.transformToSRS(thegeom, thegeomsrs, srsIRI), a.datatype,srsIRI)
    raise ValueError("An invalid geometry literal was provided or an illegal transformation requested for function geof:transform")
transformCRS84()
Literal transformCRS84 (a)
def transformCRS84(a) -> Literal:
    thegeom, thegeomsrs = LiteralUtils.processLiteralTypeToGeom(a)
    if thegeom is not None and thegeomsrs is not None:
        return LiteralUtils.processGeomToLiteral(Transformers.transformToSRS(thegeom, thegeomsrs, CRS84URI), a.datatype,
                                                 CRS84URI)
    raise ValueError(
        "An invalid geometry literal was provided or an illegal transformation requested for function geof:transformCRS84")
translate()
Literal translate (a, deltaX, deltaY, deltaZ)
def translate(a, deltaX, deltaY, deltaZ) -> Literal:
    thegeom, thegeomsrs = LiteralUtils.processLiteralTypeToGeom(a)
    if (isinstance(deltaX, Literal) and deltaX.datatype == XSD.double and isinstance(deltaY,
                                                                                     Literal) and deltaY.datatype == XSD.double and isinstance(
            deltaZ, Literal) and deltaZ.datatype == XSD.double):
        return LiteralUtils.processGeomToLiteral(
            shapely.affinity.translate(thegeom, float(deltaX.value), float(deltaY.value), float(deltaZ.value)),
            a.datatype, thegeomsrs)
    raise ValueError("Invalid parameters were provided for function geof:translate")
union()
Literal union (a, b)
def union(a, b) -> Literal:
    geomtps = LiteralUtils.processLiteralsToGeom([a, b], normalize=True)
    if len(geomtps) > 1:
        return LiteralUtils.processGeomToLiteral(shapely.union(geomtps[0][0], geomtps[1][0]), a.datatype, geomtps[0][1])
    raise ValueError("Invalid parameters were provided for function geof:union")
within()
Literal within (a, b)
def within(a, b) -> Literal:
    geoms = list(zip(*LiteralUtils.processLiteralsToGeom([a, b], normalize=True)))[0]
    if geoms[0] is not None and geoms[1] is not None:
        return Literal(shapely.within(geoms[0], geoms[1]), datatype=XSD.boolean)
    raise ValueError("Invalid parameters were provided for function geof:within")
withinDistance()
Literal withinDistance (a, b, d)
def withinDistance(a, b, d) -> Literal:
    geoms = list(zip(*LiteralUtils.processLiteralsToGeom([a, b], normalize=True)))[0]
    if isinstance(d, Literal) and d.datatype == XSD.double:
        distance = float(str(d))
        return Literal(str(shapely.dwithin(geoms[0], geoms[1], distance)), datatype=XSD.boolean)
x()
Literal x (a)
def x(a) -> Literal:
    thegeom, thegeomsrs = LiteralUtils.processLiteralTypeToGeom(a)
    if thegeom.geom_type == "Point":
        return Literal(shapely.get_x(thegeom), datatype=XSD.double)
    raise ValueError("Invalid parameters, e.g. a non-Point geometry literal was provided for function geof:x")
y()
Literal y (a)
def y(a) -> Literal:
    thegeom, thegeomsrs = LiteralUtils.processLiteralTypeToGeom(a)
    if thegeom.geom_type == "Point":
        return Literal(shapely.get_y(thegeom), datatype=XSD.double)
    raise ValueError("Invalid parameters, e.g. a non-Point geometry literal was provided for function geof:y")
z()
Literal z (a)
def z(a) -> Literal:
    thegeom, thegeomsrs = LiteralUtils.processLiteralTypeToGeom(a)
    if thegeom.geom_type == "Point" and thegeom.has_z:
        return Literal(str(shapely.get_z(thegeom)), datatype=XSD.double)
    raise ValueError(
        "Invalid parameters, e.g. a non-Point geometry literal or a non-3D geometry was provided for function geof:z")
Variable Documentation
CRS84URI
str CRS84URI = "http://www.opengis.net/def/crs/OGC/1.3/CRS84"
dir_path
dir_path = os.path.dirname(os.path.realpath(__file__))
g
g = Graph()
GEO
str GEO = "http://www.opengis.net/ont/geosparql#"
GEOF
str GEOF = "http://www.opengis.net/def/function/geosparql/"
GEOFEXT
str GEOFEXT = "http://www.opengis.net/def/function/geosparql/ext/"
GEOFEXTPREFIX
str GEOFEXTPREFIX = "geofext:"
GEOFPREFIX
str GEOFPREFIX = "geof:"
geosparql10
dict geosparql10
geosparql11
dict geosparql11
geosparql13
dict geosparql13
result
result
Initial value:
=  g.query(
    +str(GEO)++str(GEOFEXT)+
)