RDFLib GeoSPARQL: geosparql.geosparql Namespace Reference
geosparql.geosparql Namespace Reference
Classes
class Handling3D
class LiteralUtils
Utilities for the conversion between literal and geometry objects.
class SRSUtils
Utilities to get attributes from SRS.
class Transformers
Transformation functions for SRS, geocodes and DGGS systems.
Functions
merge_dicts (*dict_args)
range_overlap (start1, end1, start2, end2)
Literal above (Literal a, Literal b)
Calculates whether the first geometry is above the second geometry.
Literal above3D (Literal a, Literal b)
Calculates whether the first 3D geometry is above the 3D second geometry.
Literal area (Literal a, Literal unit)
Implements geof:area: Calculates the area of a 2D geometry provided as a geometry literal .
Literal azimuth (Literal a)
Calculates the azimuth of a 2D geometry provided as a geometry literal .
Literal asDGGS (Literal a, dggsType)
Implements geof:asDGGS: Converts a geometry literal to a DGGS literal .
Literal asGeoJSON (Literal a)
Implements geof:asGeoJSON: Converts a geometry literal to a GeoJSON literal .
Literal asGLTF (Literal a)
Converts a geometry literal to a GLTF literal .
Literal asGeocode (Literal a, geocodeURI)
Implements geof:asGeocode: Converts a geometry literal to a Geocode literal .
Literal asGML (Literal a)
Implements geof:asGML: Converts a geometry literal to a GML literal preserving its coordinate reference system.
Literal asKML (Literal a)
Implements geof:asKML: Converts a geometry literal to a KML literal.
Literal asOBJ (Literal a)
Converts a geometry literal to a OBJ literal .
Literal asPLY (Literal a)
Converts a geometry literal to a PLY literal .
Literal asSVG (Literal a)
Converts a geometry literal to a SVG literal .
Literal asXYZ (Literal a)
Converts a geometry literal to a XYZ literal .
Literal asWKB (Literal a)
Converts a geometry literal to a WKB literal.
Literal asWKT (Literal a)
Implements geof:asWKT: Converts a geometry literal to a WKT literal.
Literal behind (Literal a, Literal b)
Calculates whether the first geometry is below the second geometry.
Literal below (Literal a, Literal b)
Calculates whether the first geometry is below the second geometry.
Literal boundary (Literal a)
Implements geof:boundary: Calculates the boundary of a geometry literal.
Literal boundingCircle (Literal a)
Implements geof:boundingCircle: Calculates the minimum bounding circle of a geometry literal.
Literal buffer (Literal a, Literal radius, Literal unit="")
Implements geof:buffer: Calculates the buffer of a geometry literal with a given radius and a given unit.
Literal centroid (Literal a)
Implements geof:centroid: Calculates the centroid of a geometry literal.
Literal closestPoint (Literal a, Literal b)
Retrieves the point on the second geometry parameter which is closest to the first geometry.
Literal contains (Literal a, Literal b)
Implements geof:sfContains geof:ehContains geof:rcc8ntppi: Calculates whether the first geometry contains the second geometry.
Literal concaveHull (Literal a)
Implements geof:concaveHull: Calculates the concave hull of a geometry literal.
Literal constrainedDelaunay (Literal a)
Calculates s triangulation using the constrained delaunay algorithm.
Literal convexHull (Literal a)
Implements geof:convexHull: Calculates the convex hull of a geometry literal.
Literal coordinateDimension (Literal a)
Implements geof:coordinateDimension: Calculates the coordinate dimension of a geometry literal.
Literal compactnessRatio (Literal a)
Literal covers (Literal a, Literal b)
Implements geof:ehCovers geof:rcc8tppi: Calculates whether the first geometry covers the second geometry.
Literal coveredBy (Literal a, Literal b)
Implements geof:ehCoveredBy geof:rcc8tppi: Calculates whether the first geometry is covered by the second geometry.
Literal|None|Any crosses (Literal a, Literal b)
Implements geof:sfCrosses: Calculates whether the first geometry crosses the second geometry.
Literal delaunayTriangles (Literal a)
Calculates a delaunay triangulation on a given geometry.
Literal disjoint (Literal a, Literal b)
Implements geof:sfDisjoint geof:ehDisjoint geof:rcc8dc: Calculates whether the two input geometries are disjoint.
Literal difference (Literal a, Literal b)
Implements geof:difference: Calculates the difference of two geometry literals.
Literal difference3D (Literal a, Literal b)
Literal distance (Literal a, Literal b, Literal units)
Implements geof:distance: Retrieves the distance between two geometries.
Literal distance3D (Literal a, Literal b)
Retrieves the distance between two geometries in 3D.
Literal endPoint (Literal a)
Extracts the last point of an input geometry.
Literal equals (Literal a, Literal b)
Implements geof:sfEquals geof:ehEquals geof:rcc8eq: Calculates whether the two input geometries are equal.
Literal envelope (Literal a)
Implements geof:envelope: Calculates a bounding box around the given geometry.
Literal extrude (Literal a, Literal extrudeval)
Extrudes a geometry to a fixed Z value.
Literal exteriorRing (Literal a)
Extracts an exerior ring from a geometry if it exists.
Literal farthestCoordinate (Literal a, Literal b)
Retrieves the farthest coordinate on a geometry to a given point.
Literal flipXY (Literal a)
Flips the XY coordinates included in the given geometry.
Literal force2D (Literal a)
Removes Z coordinates from the given geometry to make it twodimensional.
Literal forceCW (Literal a)
Sets a clockwise ring orientation on the exterior ring of a polygon.
Literal forceCCW (Literal a)
Sets a counterclockwise ring orientation on the exterior ring of a polygon.
Literal frechetDistance (Literal a, Literal b)
Calculates the FrechetDistance between two input geometries.
Literal geometryN (Literal a, Literal n)
Implements geof:geometryN: Returns the nth geometry of a GeometryCollection if it exists.
Literal geometryType (Literal a)
Implements geof:geometryType: Retrieves the geometry type of a geometry literal.
Literal getSRID (Literal a)
Implements geof:getSRID: Retrieves the SRID URI of a geometry.
Literal hausdorffDistance (Literal a, Literal b)
Calculates the HausdorffDistance between two input geometries.
Literal inside (Literal a, Literal b)
Implements geof:ehInside geof:rcc8ntpp: Calculates whether the first geometry is inside the second geometry.
Literal interpolatePoint (Literal a, Literal d)
Returns a point interpolated at a given distance on a line.
Literal intersection (Literal a, Literal b)
Implements geof:intersection: Calculates the intersection of two geometry literals.
Literal intersection3D (Literal a, Literal b)
Literal intersects (Literal a, Literal b)
Implements geof:sfIntersects: Calculates whether the two input geometries intersect.
Literal intersects3D (Literal a, Literal b)
Literal is3D (Literal a)
Implements geof:is3D: Calculates whether a geometry literal represents a 3D geometry.
Literal isCCW (Literal a)
Checks whether the coordinates of a LineString or LinearRing are counterclockwise.
Literal isCollection (Literal a)
Indicates whether a geometry literal contains a GeometryCollection.
Literal isClosed (Literal a)
Implements geof:isClosed: Calculates whether a geometry literal represents a closed geometry.
Literal isEmpty (Literal a)
Implements geof:isEmpty: Calculates whether a geometry literal represents a closed geometry.
Literal isMeasured (Literal a)
Implements geof:isMeasured: Calculates whether a geometry literal has measurement coordinates.
Literal isRectangle (Literal a)
Calculates whether a geometry literal represents a rectangle.
Literal isRing (Literal a)
Implements geof:isRing: Calculates whether a geometry literal is a ring.
Literal isSimple (Literal a)
Implements geof:isSimple: Calculates whether a geometry literal represents a simple geometry.
Literal isTriangle (Literal a)
Calculates whether a geometry is a triangle.
Literal isValid (Literal a)
Calculates whether a geometry literal represents a valid geometry.
Literal isValidTrajectory (Literal a)
Calculates whether a geometry literal encodes a valid trajectory.
Literal leftOf (Literal a, Literal b)
Calculates whether the first geometry is left of the second geometry.
Literal length (Literal a, Literal unit)
Implements geof:length: Retrieves the length of a geometry.
Literal longestLine (Literal a, Literal b)
Retrieves the longest line between two geometries defined by the two points with maximum distance.
Literal m (Literal a)
Retrieves the M coordinate of a Point geometry.
Literal makeValid (Literal a)
Creates a valid version of an invalid geometry.
Literal matrixTransform (Literal a, matrix)
Literal maxDistance (Literal a, Literal b)
Retrieves the maximum distance between two geometries.
Literal maxM (Literal a)
Retrieves the maximum measurement coordinate of a geometry.
Literal maxX (Literal a)
Implements geof:maxX: Retrieves the maximum x coordinate of a geometry.
Literal maxY (Literal a)
Implements geof:maxY: Retrieves the maximum y coordinate of a geometry.
Literal maxZ (Literal a)
Implements geof:maxZ: Retrieves the maximum z coordinate of a geometry.
Literal metricArea (Literal a)
Implements geof:metricArea: Calculates the area of a 2D geometry provided as a geometry literal in squaremeters.
Literal metricBuffer (Literal a, Literal radius)
Implements geof:metricBuffer: Calculates a buffer of a 2D geometry from a given radius.
Literal metricDistance (Literal a, Literal b)
Implements geof:metricDistance: Retrieves the distance between two geometries in meters.
Literal metricLength (Literal a)
Implements geof:metricLength: Retrieves the length of a geometry in meters.
Literal metricPerimeter (Literal a)
Implements geof:metricPerimeter: Retrieves the perimeter length of a geometry in meters.
Literal metricWithinDistance (Literal a, b, d)
Calculates whether the first geometry is within a given distance to the second geometry.
Literal minimumBoundingRadius (Literal a)
Calculates the radius of the minimum bounding circle around the input geometry.
Literal minimumClearance (Literal a)
Calculates the minimum clearance of the input geometry.
Literal minimumClearanceLine (Literal a)
Retrieves the minimum clearance line of a geometry.
Literal minM (Literal a)
Retrieves the minimum measurement coordinate of a geometry.
Literal minX (Literal a)
Implements geof:minX: Retrieves the minimum X coordinate of a geometry.
Literal minY (Literal a)
Implements geof:minY: Retrieves the minimum Y coordinate of a geometry.
Literal minZ (Literal a)
Implements geof:minZ: Retrieves the minimum z coordinate of a geometry.
Literal numGeometries (Literal a)
Implements geof:numGeometries: Calculates the number of geometries included in the geometry literal.
Literal numInteriorRing (Literal a)
Implements geof:numInteriorRing: Calculates the number of interior rings included in the geometry literal.
Literal numPatches (Literal a)
Implements geof:numPatches: Calculates the number of patches included in the geometry literal.
Literal numPoints (Literal a)
Implements geof:numPoints: Calculates the number of points included in the geometry literal.
Literal offsetCurve (Literal a, Literal d)
Creates an offset line at a given distance and side from an input geometry .
Literal overlaps (Literal a, Literal b)
Implements geof:sfOverlaps geof:ehOverlap geof:rcc8po: Calculates whether the two input geometries overlap.
Literal patchN (Literal a, Literal n)
Implements geof:patchN: Returns the nth patch of a geometry.
Literal pointN (Literal a, n)
Implements geof:pointN: Returns the nth point of a geometry.
Literal pointOnSurface (Literal a)
Returns a point on the surface of the given geometry.
Literal perimeter (Literal a, Literal unit)
Implements geof:perimeter: Retrieves the perimeter length of a geometry.
Literal relate (Literal a, Literal b, Literal matrix)
Implements geof:relate: Calculates whether two input geometries conform to a given DE-9IM pattern.
Literal removeRepeatedPoints (Literal a)
Creates a geometry without repeated points.
Literal reverse (Literal a)
Returns a version of the input geometry with reversed point order.
Literal rightOf (Literal a, Literal b)
Calculates whether the first geometry is right of the second geometry.
Literal rotate (Literal a, Literal angle)
Implements geof:relate: Calculates whether two input geometries conform to a given DE-9IM pattern.
Literal scale (Literal a, Literal scaleX, Literal scaleY, Literal scaleZ)
Returns a scaled version of the input geometry.
Literal shortestLine (Literal a, Literal b)
Retrieves the shortest line between two geometries defined by the two points with minimum distance.
Literal simplify (Literal a, Literal tolerance)
Returns a simplfied version of the input geometry calculated with the Douglas Peucker simplification algoritm.
Literal skew (Literal a, Literal xs, Literal ys)
Returns a skewed version of the input geometry.
Literal spatialDimension (Literal a)
Implements geof:spatialDimension: Calculates the spatial dimension of a geometry literal.
Literal startPoint (Literal a)
Extracts the first point of an input geometry.
Literal symDifference (Literal a, Literal b)
Implements geof:symDifference: Calculates the symmetric difference of two geometry literals.
Literal transform (Literal a, Literal srsIRI)
Implements geof:transform: Transforms a given geometry literal to a given CRS.
Literal transformCRS84 (Literal a)
Transforms a given geometry literal to the CRS84 CRS.
Literal translate (Literal a, Literal deltaX, Literal deltaY, Literal deltaZ)
Returns a translated version of the input geometry.
Literal touches (Literal a, Literal b)
Implements geof:sfTouches geof:ehMeet geof:rcc8ec: Calculates whether the two input geometries touch.
Literal union (Literal a, Literal b)
Implements geof:union: Calculates the union of two geometry literals.
Literal union3D (Literal a, Literal b)
Implements geof:union: Calculates the union of two geometry literals.
Literal within (Literal a, Literal b)
Implements geof:sfWithin: Calculates whether the first geometry is within the second geometry.
Literal withinDistance (Literal a, Literal b, Literal d, Literal unit)
Calculates whether the first geometry is within a given distance to the second geometry.
Literal x (Literal a)
Retrieves the X coordinate of a Point geometry.
Literal y (Literal a)
Retrieves the Y coordinate of a Point geometry.
Literal z (Literal a)
Retrieves the Z coordinate of a Point geometry.
getfuncs ()
Variables
str GEOF = "http://www.opengis.net/def/function/geosparql/"
str GEOFEXT = "http://www.opengis.net/def/function/geosparql/ext/"
str GEOFPREFIX = "geof:"
str GEOFEXTPREFIX = "geofext:"
str GEO = "http://www.opengis.net/ont/geosparql#"
str CRS84URI = "http://www.opengis.net/def/crs/OGC/1.3/CRS84"
dict geosparql10
dict geosparql11
dict geosparql13
g = Graph()
dir_path = os.path.dirname(os.path.realpath(__file__))
result
Function Documentation
above()
Literal above (Literal a, Literal b)
Calculates whether the first geometry is above the second geometry.
Parameters
a The first geometry literal
b The second geometry literal
Returns
A xsd:boolean Literal indicating whether the first geometry is above the second geometry
def above(a: Literal, b: Literal) -> Literal:
    geoms = list(zip(*LiteralUtils.processLiteralsToGeom([a, b], normalize=True)))[0]
    if geoms[0] is not None and geoms[1] is not None:
        #geom[0].maxY>geom[1].minY
        geom1bounds=shapely.total_bounds(geoms[0])
        geom2bounds=shapely.total_bounds(geoms[1])
        ro=range_overlap(geom1bounds[0],geom1bounds[2],geom2bounds[0],geom2bounds[2])
        return Literal(ro>0 and geom1bounds[3]>geom2bounds[1], datatype=XSD.boolean)
References geosparql.geosparql.range_overlap().
above3D()
Literal above3D (Literal a, Literal b)
Calculates whether the first 3D geometry is above the 3D second geometry.
Parameters
a The first geometry literal
b The second geometry literal
Returns
A xsd:boolean Literal indicating whether the first geometry is above the second geometry
def above3D(a: Literal, b: Literal) -> Literal:
    geoms = list(zip(*LiteralUtils.processLiteralsToGeom([a, b], normalize=True)))[0]
    if geoms[0] is not None and geoms[1] is not None:
        #geom[0].maxY>geom[1].minY and
        geom1bounds=shapely.total_bounds(geoms[0])
        geom2bounds=shapely.total_bounds(geoms[1])
        rox=range_overlap(geom1bounds[0],geom1bounds[2],geom2bounds[0],geom2bounds[2])
        roz=range_overlap(Handling3D.minZ(geoms[0]),Handling3D.maxZ(geoms[0]),Handling3D.minZ(geoms[1]),Handling3D.maxZ(geoms[1]))
        return Literal(rox>0 and roz>0 and geom1bounds[3]>geom2bounds[1], datatype=XSD.boolean)
References geosparql.geosparql.range_overlap().
area()
Literal area (Literal a, Literal unit)
Implements geof:area: Calculates the area of a 2D geometry provided as a geometry literal .
Parameters
a The geometry literal.
unit The unit in which to represent the area.
Returns
The area as an xsd:double Literal
def area(a: Literal, unit: Literal) -> Literal:
    if unit.value not in SRSUtils.uniturisToUnit:
        raise ValueError("The provided unit "+str(unit)+" is not a supported unit.\nSupported units: "+str(SRSUtils.uniturisToUnit.keys()))
    thegeom, thegeomsrs = LiteralUtils.processLiteralTypeToGeom(a)
    normgeom = Transformers.transformToSRS(thegeom, thegeomsrs, 3857)
    thearea=shapely.area(normgeom)
    if SRSUtils.uniturisToUnit[unit.value]!="squaremeter":
        thearea=SRSUtils.convertMetricToUnit(thearea,"http://qudt.org/vocab/unit/M2",unit.value)
    return Literal(thearea, datatype=XSD.double)
asDGGS()
Literal asDGGS (Literal a, dggsType)
Implements geof:asDGGS: Converts a geometry literal to a DGGS literal .
Parameters
a The geometry literal
dggsType The DGGS type described by a URI
Returns
The geometry as a geo:dggsLiteral
def asDGGS(a: Literal, dggsType) -> Literal:
    thegeom, thegeomsrs = LiteralUtils.processLiteralTypeToGeom(a)
    #print(a: Literal)
    #print(dggsType)
    #print(Transformers.transformToDGGS(thegeom, dggsType))
    return Literal(Transformers.transformToDGGS(thegeom, dggsType),datatype="http://www.opengis.net/ont/geosparql#dggsLiteral")
asGeocode()
Literal asGeocode (Literal a, geocodeURI)
Implements geof:asGeocode: Converts a geometry literal to a Geocode literal .
Parameters
a The geometry literal
geocodeURI The Geocode type described by a URI
Returns
The geometry as a geo:geocodeLiteral
def asGeocode(a: Literal, geocodeURI) -> Literal:
    thegeom, thegeomsrs = LiteralUtils.processLiteralTypeToGeom(a)
    print(thegeom)
    print(geocodeURI)
    return Literal(Transformers.transformToGeocode(thegeom, str(geocodeURI)),
                   datatype="http://www.opengis.net/ont/geosparql#geocodeLiteral")
asGeoJSON()
Literal asGeoJSON (Literal a)
Implements geof:asGeoJSON: Converts a geometry literal to a GeoJSON literal .
Parameters
a The geometry literal
Returns
The geometry as a geo:geoJSONLiteral
def asGeoJSON(a: Literal) -> Literal:
    if a.datatype=="http://www.opengis.net/ont/geosparql#geoJSONLiteral":
        return a
    thegeom, thegeomsrs = LiteralUtils.processLiteralTypeToGeom(a)
    return LiteralUtils.processGeomToLiteral(thegeom, "http://www.opengis.net/ont/geosparql#geoJSONLiteral", thegeomsrs)
asGLTF()
Literal asGLTF (Literal a)
Converts a geometry literal to a GLTF literal .
Parameters
a The geometry literal
Returns
The geometry as a geo:gltfLiteral
def asGLTF(a: Literal) -> Literal:
    if a.datatype=="http://www.opengis.net/ont/geosparql#gltfLiteral":
        return a
    thegeom, thegeomsrs = LiteralUtils.processLiteralTypeToGeom(a, create3D=True)
    return LiteralUtils.processGeomToLiteral(thegeom, "http://www.opengis.net/ont/geosparql#gltfLiteral", thegeomsrs)
asGML()
Literal asGML (Literal a)
Implements geof:asGML: Converts a geometry literal to a GML literal preserving its coordinate reference system.
Parameters
a The geometry literal
Returns
The geometry as a geo:gmlLiteral
def asGML(a: Literal) -> Literal:
    if a.datatype=="http://www.opengis.net/ont/geosparql#gmlLiteral":
        return a
    thegeom, thegeomsrs = a.value #LiteralUtils.processLiteralTypeToGeom(a)
    print("THE GEOM GML: "+str(thegeom))
    return LiteralUtils.processGeomToLiteral(thegeom, "http://www.opengis.net/ont/geosparql#gmlLiteral", thegeomsrs)
asKML()
Literal asKML (Literal a)
Implements geof:asKML: Converts a geometry literal to a KML literal.
Parameters
a The geometry literal
Returns
The geometry as a geo:kmlLiteral
def asKML(a: Literal) -> Literal:
    if a.datatype=="http://www.opengis.net/ont/geosparql#kmlLiteral":
        return a
    thegeom, thegeomsrs = LiteralUtils.processLiteralTypeToGeom(a)
    return LiteralUtils.processGeomToLiteral(thegeom, "http://www.opengis.net/ont/geosparql#kmlLiteral", thegeomsrs)
asOBJ()
Literal asOBJ (Literal a)
Converts a geometry literal to a OBJ literal .
Parameters
a The geometry literal
Returns
The geometry as a geo:objLiteral
def asOBJ(a: Literal) -> Literal:
    if a.datatype=="http://www.opengis.net/ont/geosparql#objLiteral":
        return a
    thegeom, thegeomsrs = LiteralUtils.processLiteralTypeToGeom(a, create3D=True)
    return LiteralUtils.processGeomToLiteral(thegeom, "http://www.opengis.net/ont/geosparql#objLiteral", thegeomsrs)
asPLY()
Literal asPLY (Literal a)
Converts a geometry literal to a PLY literal .
Parameters
a The geometry literal
Returns
The geometry as a geo:plyLiteral
def asPLY(a: Literal) -> Literal:
    if a.datatype=="http://www.opengis.net/ont/geosparql#plyLiteral":
        return a
    thegeom, thegeomsrs = LiteralUtils.processLiteralTypeToGeom(a, create3D=True)
    return LiteralUtils.processGeomToLiteral(thegeom, "http://www.opengis.net/ont/geosparql#plyLiteral", thegeomsrs)
asSVG()
Literal asSVG (Literal a)
Converts a geometry literal to a SVG literal .
Parameters
a The geometry literal
Returns
The geometry as a geo:svgLiteral
def asSVG(a: Literal) -> Literal:
    if a.datatype=="http://www.opengis.net/ont/geosparql#svgLiteral":
        return a
    thegeom, thegeomsrs = LiteralUtils.processLiteralTypeToGeom(a)
    return LiteralUtils.processGeomToLiteral(thegeom, "http://www.opengis.net/ont/geosparql#svgLiteral", thegeomsrs)
asWKB()
Literal asWKB (Literal a)
Converts a geometry literal to a WKB literal.
Implements geof:asWKB
Parameters
a The geometry literal
Returns
The geometry as a geo:wkbLiteral
def asWKB(a: Literal) -> Literal:
    if a.datatype=="http://www.opengis.net/ont/geosparql#wkbLiteral":
        return a
    thegeom, thegeomsrs = LiteralUtils.processLiteralTypeToGeom(a)
    return LiteralUtils.processGeomToLiteral(thegeom, "http://www.opengis.net/ont/geosparql#wkbLiteral", thegeomsrs)
asWKT()
Literal asWKT (Literal a)
Implements geof:asWKT: Converts a geometry literal to a WKT literal.
Parameters
a The geometry literal
Returns
The geometry as a geo:wktLiteral
def asWKT(a: Literal) -> Literal:
    if a.datatype=="http://www.opengis.net/ont/geosparql#wktLiteral":
        return a
    thegeom, thegeomsrs = LiteralUtils.processLiteralTypeToGeom(a)
    return LiteralUtils.processGeomToLiteral(thegeom, "http://www.opengis.net/ont/geosparql#wktLiteral", thegeomsrs)
asXYZ()
Literal asXYZ (Literal a)
Converts a geometry literal to a XYZ literal .
Parameters
a The geometry literal
Returns
The geometry as a geo:xyzLiteral
def asXYZ(a: Literal) -> Literal:
    if a.datatype=="http://www.opengis.net/ont/geosparql#xyzLiteral":
        return a
    thegeom, thegeomsrs = LiteralUtils.processLiteralTypeToGeom(a, create3D=True)
    return LiteralUtils.processGeomToLiteral(thegeom, "http://www.opengis.net/ont/geosparql#xyzLiteral", thegeomsrs)
azimuth()
Literal azimuth (Literal a)
Calculates the azimuth of a 2D geometry provided as a geometry literal .
Parameters
a The geometry literal.
Returns
The azimuth as an xsd:double Literal
def azimuth(a: Literal) -> Literal:
    thegeom, thegeomsrs = LiteralUtils.processLiteralTypeToGeom(a)
    minrect = thegeom.minimum_rotated_rectangle
    minrectb = minrect.boundary
    coords = [c for c in minrectb.coords]  # List the line coordinates
    segments = [shapely.geometry.LineString([a, b]) for a, b in zip(coords, coords[1:])]  # Create the four side lines.
    longest_segment = max(segments, key=lambda x: x.length)
    p1, p2 = [c for c in longest_segment.coords]  # List the start and end coordinates of it
    azimuthangle = degrees(atan2(p2[1] - p1[1], p2[0] - p1[0]))
    return Literal(azimuthangle, datatype=XSD.double)
behind()
Literal behind (Literal a, Literal b)
Calculates whether the first geometry is below the second geometry.
Parameters
a The first geometry literal
b The second geometry literal
Returns
A xsd:boolean Literal indicating whether the first geometry is below the second geometry
def behind(a: Literal, b: Literal) -> Literal:
    geoms = list(zip(*LiteralUtils.processLiteralsToGeom([a, b], normalize=True)))[0]
    if geoms[0] is not None and geoms[1] is not None:
        #geom[0].maxZ<geom[1].minZ
        geom1bounds=shapely.total_bounds(geoms[0])
        geom2bounds = shapely.total_bounds(geoms[1])
        rox=range_overlap(geom1bounds[0],geom1bounds[2],geom2bounds[0],geom2bounds[2])
        roy=range_overlap(geom1bounds[1],geom1bounds[3],geom2bounds[1],geom2bounds[3])
        geom1maxZ=Handling3D.maxZ(geoms[0])
        geom2minZ=Handling3D.minZ(geoms[1])
        return Literal(rox>0 and roy>0 and geom1maxZ<geom2minZ, datatype=XSD.boolean)
References geosparql.geosparql.range_overlap().
below()
Literal below (Literal a, Literal b)
Calculates whether the first geometry is below the second geometry.
Parameters
a The first geometry literal
b The second geometry literal
Returns
A xsd:boolean Literal indicating whether the first geometry is below the second geometry
def below(a: Literal, b: Literal) -> Literal:
    geoms = list(zip(*LiteralUtils.processLiteralsToGeom([a, b], normalize=True)))[0]
    if geoms[0] is not None and geoms[1] is not None:
        #geom[0].maxY<geom[1].minY
        geom1bounds=shapely.total_bounds(geoms[0])
        geom2bounds=shapely.total_bounds(geoms[1])
        ro=range_overlap(geom1bounds[0],geom1bounds[2],geom2bounds[0],geom2bounds[2])
        return Literal(ro>0 and geom1bounds[3]<geom2bounds[1], datatype=XSD.boolean)
References geosparql.geosparql.range_overlap().
boundary()
Literal boundary (Literal a)
Implements geof:boundary: Calculates the boundary of a geometry literal.
Parameters
a The geometry literal
Returns
The geometry as a geometry literal in the CRS and literal format of the input geometry
def boundary(a: Literal) -> Literal:
    thegeom, thegeomsrs = LiteralUtils.processLiteralTypeToGeom(a)
    return LiteralUtils.processGeomToLiteral(shapely.boundary(thegeom), a.datatype, thegeomsrs)
boundingCircle()
Literal boundingCircle (Literal a)
Implements geof:boundingCircle: Calculates the minimum bounding circle of a geometry literal.
Parameters
a The geometry literal
Returns
The bounding circle as a geometry literal in the CRS and literal format of the input geometry
def boundingCircle(a: Literal) -> Literal:
    thegeom, thegeomsrs = a.value#LiteralUtils.processLiteralTypeToGeom(a)
    return LiteralUtils.processGeomToLiteral(shapely.minimum_bounding_circle(thegeom), a.datatype, thegeomsrs)
buffer()
Literal buffer (Literal a, Literal radius, Literal unit = "")
Implements geof:buffer: Calculates the buffer of a geometry literal with a given radius and a given unit.
Parameters
a The geometry literal
radius The buffer radius
unit the radius unit
Returns
The buffer as a geometry literal in the CRS and literal format of the input geometry
def buffer(a: Literal, radius: Literal, unit: Literal="") -> Literal:
    thegeom, thegeomsrs = LiteralUtils.processLiteralTypeToGeom(a)
    if isinstance(radius, Literal) and radius.datatype == XSD.double:
        return LiteralUtils.processGeomToLiteral(shapely.buffer(thegeom, float(radius)), a.datatype, thegeomsrs)
centroid()
Literal centroid (Literal a)
Implements geof:centroid: Calculates the centroid of a geometry literal.
Parameters
a The geometry literal
Returns
The centroid as a geometry literal in the CRS of the input geometry
def centroid(a: Literal) -> Literal:
    thegeom, thegeomsrs = LiteralUtils.processLiteralTypeToGeom(a)
    return LiteralUtils.processGeomToLiteral(thegeom.centroid, a.datatype, thegeomsrs)
closestPoint()
Literal closestPoint (Literal a, Literal b)
Retrieves the point on the second geometry parameter which is closest to the first geometry.
Parameters
a The first geometry literal
b The second geometry literal
Returns
The closest point on the first geometry to the second geometry as a geometry literal of the same type and CRS as the first input geometry
def closestPoint(a: Literal, b: Literal) -> Literal:
    geoms = list(zip(*LiteralUtils.processLiteralsToGeom([a, b], normalize=True)))[0]
    if geoms[0].has_z and geoms[1].has_z:
        g1list = shapely.get_coordinates(geoms[0], include_z=True).tolist()
        g2list = shapely.get_coordinates(geoms[1], include_z=True).tolist()
    else:
        g1list = shapely.get_coordinates(geoms[0], include_z=False).tolist()
        g2list = shapely.get_coordinates(geoms[1], include_z=False).tolist()
    mindistance=float("inf")
    closest=None
    for p1 in g1list:
        for p2 in g2list:
            cp = shapely.geometry.Point(p1)
            dist = shapely.distance(cp, shapely.geometry.Point(p2))
            if dist<mindistance:
                mindistance=dist
                closest=cp
    if closest is not None:
        return LiteralUtils.processGeomToLiteral(closest,a.datatype,"")
compactnessRatio()
Literal compactnessRatio (Literal a)
def compactnessRatio(a: Literal) -> Literal:
    thegeom, thegeomsrs = LiteralUtils.processLiteralTypeToGeom(a)
    p = thegeom.length
    a = thegeom.area
    return Literal(str(1 / (p / (2 * pi * sqrt(a / pi)))), datatype=XSD.double)
concaveHull()
Literal concaveHull (Literal a)
Implements geof:concaveHull: Calculates the concave hull of a geometry literal.
Parameters
a The geometry literal
Returns
The concave hull as a geometry literal in the format and CRS of the input geometry
def concaveHull(a: Literal) -> Literal:
    thegeom, thegeomsrs = LiteralUtils.processLiteralTypeToGeom(a)
    return LiteralUtils.processGeomToLiteral(shapely.concave_hull(thegeom), a.datatype, thegeomsrs)
constrainedDelaunay()
Literal constrainedDelaunay (Literal a)
Calculates s triangulation using the constrained delaunay algorithm.
Parameters
a The geometry literal
Returns
The constrained delaunay triangulation result as a geometry literal in the format and CRS of the input geometry
def constrainedDelaunay(a: Literal) -> Literal:
    thegeom, thegeomsrs = LiteralUtils.processLiteralTypeToGeom(a)
    return LiteralUtils.processGeomToLiteral(shapely.constrained_delaunay_triangles(thegeom), a.datatype, thegeomsrs)
contains()
Literal contains (Literal a, Literal b)
Implements geof:sfContains geof:ehContains geof:rcc8ntppi: Calculates whether the first geometry contains the second geometry.
Parameters
a The first geometry literal
b The second geometry literal
Returns
A xsd:boolean Literal indicating whether the first geometry contains the second geometry
def contains(a: Literal, b: Literal) -> Literal:
    geoms = list(zip(*LiteralUtils.processLiteralsToGeom([a, b], normalize=True)))[0]
    if geoms[0] is not None and geoms[1] is not None:
        return Literal(shapely.contains(geoms[0], geoms[1]), datatype=XSD.boolean)
convexHull()
Literal convexHull (Literal a)
Implements geof:convexHull: Calculates the convex hull of a geometry literal.
Parameters
a The geometry literal
Returns
The convex hull as a geometry literal in the CRS of the input geometry
def convexHull(a: Literal) -> Literal:
    thegeom, thegeomsrs = LiteralUtils.processLiteralTypeToGeom(a)
    return LiteralUtils.processGeomToLiteral(thegeom.convex_hull, a.datatype, thegeomsrs)
coordinateDimension()
Literal coordinateDimension (Literal a)
Implements geof:coordinateDimension: Calculates the coordinate dimension of a geometry literal.
Parameters
a The geometry literal
Returns
The coordinate dimension as a xsd:integer Literal
def coordinateDimension(a: Literal) -> Literal:
    thegeom, thegeomsrs = LiteralUtils.processLiteralTypeToGeom(a)
    return Literal(shapely.get_coordinate_dimension(thegeom), datatype=XSD.integer)
coveredBy()
Literal coveredBy (Literal a, Literal b)
Implements geof:ehCoveredBy geof:rcc8tppi: Calculates whether the first geometry is covered by the second geometry.
Parameters
a The first geometry literal
b The second geometry literal
Returns
A xsd:boolean Literal indicating whether the first geometry is covered by the second geometry
def coveredBy(a: Literal, b: Literal) -> Literal:
    geoms = list(zip(*LiteralUtils.processLiteralsToGeom([a, b], normalize=True)))[0]
    if geoms[0] is not None and geoms[1] is not None:
        return Literal(shapely.covered_by(geoms[0], geoms[1]), datatype=XSD.boolean)
covers()
Literal covers (Literal a, Literal b)
Implements geof:ehCovers geof:rcc8tppi: Calculates whether the first geometry covers the second geometry.
Parameters
a The first geometry literal
b The second geometry literal
Returns
A xsd:boolean Literal indicating whether the first geometry covers the second geometry
def covers(a: Literal, b: Literal) -> Literal:
    geoms = list(zip(*LiteralUtils.processLiteralsToGeom([a, b], normalize=True)))[0]
    if geoms[0] is not None and geoms[1] is not None:
        return Literal(shapely.covers(geoms[0], geoms[1]), datatype=XSD.boolean)
crosses()
Literal | None | Any crosses (Literal a, Literal b)
Implements geof:sfCrosses: Calculates whether the first geometry crosses the second geometry.
Parameters
a The first geometry literal
b The second geometry literal
Returns
A xsd:boolean Literal indicating whether the first geometry crosses the second geometry
def crosses(a: Literal, b: Literal) -> Literal | None | Any:
    geoms = list(zip(*LiteralUtils.processLiteralsToGeom([a, b], normalize=True)))[0]
    if geoms[0] is not None and geoms[1] is not None:
        return Literal(shapely.crosses(geoms[0], geoms[1]), datatype=XSD.boolean)
delaunayTriangles()
Literal delaunayTriangles (Literal a)
Calculates a delaunay triangulation on a given geometry.
Parameters
a The geometry literal
Returns
The delaunay triangulation result as a geometry literal in the format and CRS of the input geometry
def delaunayTriangles(a: Literal) -> Literal:
    thegeom, thegeomsrs = LiteralUtils.processLiteralTypeToGeom(a)
    return LiteralUtils.processGeomToLiteral(shapely.delaunay_triangles(thegeom), a.datatype, thegeomsrs)
difference()
Literal difference (Literal a, Literal b)
Implements geof:difference: Calculates the difference of two geometry literals.
Parameters
a The first geometry literal
b The second geometry literal
Returns
The difference as a geometry literal in the CRS and literal format of the first input geometry
def difference(a: Literal, b: Literal) -> Literal:
    geomtps = LiteralUtils.processLiteralsToGeom([a, b], normalize=True)
    print(geomtps)
    print(shapely.difference(geomtps[0][0], geomtps[1][0]))
    if len(geomtps) > 1:
        return LiteralUtils.processGeomToLiteral(shapely.difference(geomtps[0][0], geomtps[1][0]), a.datatype,
                                                 geomtps[0][1])
Referenced by geosparql.geosparql.difference3D().
difference3D()
Literal difference3D (Literal a, Literal b)
def difference3D(a: Literal, b: Literal) -> Literal:
    print("DIFF 3D")
    geoms = list(zip(*LiteralUtils.processLiteralsToGeom([a, b], normalize=True, create3D=True)))[0]
    """
    print("GEOMS: "+str(geoms))
    diff=geoms[0].difference(geoms[1])
    print("DIFF: "+str(diff))
    bio = BytesIO()
    diff.export(bio, file_type="ply", encoding='ascii')
    res=bio.getvalue().decode("utf-8")
    print("DIFF AS PLY: "+str(res))
    print(geoms[0].difference(geoms[1]).volume)
    """
    if geoms[0] is not None and geoms[1] is not None:
        diff=geoms[0].difference(geoms[1])
        bio = BytesIO()
        diff.export(bio, file_type="ply", encoding='ascii')
        res = bio.getvalue().decode("utf-8")
        return LiteralUtils.processGeomToLiteral(diff,a.datatype)
References geosparql.geosparql.difference().
disjoint()
Literal disjoint (Literal a, Literal b)
Implements geof:sfDisjoint geof:ehDisjoint geof:rcc8dc: Calculates whether the two input geometries are disjoint.
Parameters
a The first geometry literal
b The second geometry literal
Returns
A xsd:boolean Literal indicating whether the two geometries are disjoint
def disjoint(a: Literal, b: Literal) -> Literal:
    geoms = list(zip(*LiteralUtils.processLiteralsToGeom([a, b], normalize=True)))[0]
    print(geoms[0])
    print(geoms[1])
    if geoms[0] is not None and geoms[1] is not None:
        return Literal(shapely.disjoint(geoms[0], geoms[1]), datatype=XSD.boolean)
distance()
Literal distance (Literal a, Literal b, Literal units)
Implements geof:distance: Retrieves the distance between two geometries.
Parameters
a The first geometry literal
b The second geometry literal
units The unit in which to return the distance as a URI
Returns
The distance as a xsd:double Literal
def distance(a: Literal, b: Literal, units: Literal) -> Literal:
    geoms = list(zip(*LiteralUtils.processLiteralsToGeom([a, b], normalize=True)))[0]
    if geoms[0] is not None and geoms[1] is not None:
        if geoms[0].has_z and geoms[1].has_z:
            return Literal(Handling3D.distance3D(geoms[0],geoms[1]), datatype=XSD.double)
        return Literal(shapely.distance(geoms[0], geoms[1]), datatype=XSD.double)
distance3D()
Literal distance3D (Literal a, Literal b)
Retrieves the distance between two geometries in 3D.
Parameters
a The first geometry literal
b The second geometry literal
Returns
The distance as a xsd:double Literal
def distance3D(a: Literal, b: Literal) -> Literal:
    geoms = list(zip(*LiteralUtils.processLiteralsToGeom([a, b], normalize=True)))[0]
    if geoms[0] is not None and geoms[1] is not None:
        return Literal(Handling3D.distance3D(geoms[0],geoms[1]), datatype=XSD.double)
endPoint()
Literal endPoint (Literal a)
Extracts the last point of an input geometry.
Parameters
a The geometry literal
Returns
The end point as a geometry literal in the CRS and literal format of the input geometry
def endPoint(a: Literal) -> Literal:
    thegeom, thegeomsrs = LiteralUtils.processLiteralTypeToGeom(a)
    return LiteralUtils.processGeomToLiteral(shapely.Point(shapely.get_coordinates(thegeom)[-1]), a.datatype,
                                             thegeomsrs)
envelope()
Literal envelope (Literal a)
Implements geof:envelope: Calculates a bounding box around the given geometry.
Parameters
a The geometry literal
Returns
The envelope of the given geometry as a geometry literal of the same type and CRS as the input geometry
def envelope(a: Literal) -> Literal:
    thegeom, thegeomsrs = LiteralUtils.processLiteralTypeToGeom(a)
    return LiteralUtils.processGeomToLiteral(thegeom.envelope, a.datatype, thegeomsrs)
equals()
Literal equals (Literal a, Literal b)
Implements geof:sfEquals geof:ehEquals geof:rcc8eq: Calculates whether the two input geometries are equal.
Parameters
a The first geometry literal
b The second geometry literal
Returns
A xsd:boolean Literal indicating whether the two geometries are equal
def equals(a: Literal, b: Literal) -> Literal:
    geoms = list(zip(*LiteralUtils.processLiteralsToGeom([a, b], normalize=True)))[0]
    if geoms[0] is not None and geoms[1] is not None:
        return Literal(shapely.equals(geoms[0], geoms[1]), datatype=XSD.boolean)
exteriorRing()
Literal exteriorRing (Literal a)
Extracts an exerior ring from a geometry if it exists.
Parameters
a The geometry literal
Returns
The exterior ring geometry as a geometry literal of the same type and CRS as the input geometry
def exteriorRing(a: Literal) -> Literal:
    thegeom, thegeomsrs = LiteralUtils.processLiteralTypeToGeom(a)
    return LiteralUtils.processGeomToLiteral(shapely.get_exterior_ring(thegeom), a.datatype, thegeomsrs)
extrude()
Literal extrude (Literal a, Literal extrudeval)
Extrudes a geometry to a fixed Z value.
Parameters
a The geometry literal
The extrusion value
Returns
The extruded geometry as a geometry literal of the same type and CRS as the input geometry
def extrude(a: Literal, extrudeval: Literal) -> Literal:
    thegeom, thegeomsrs = LiteralUtils.processLiteralTypeToGeom(a)
    return LiteralUtils.processGeomToLiteral(shapely.force_3d(shapely.force_2d(thegeom), extrudeval), a.datatype,
                                             thegeomsrs)
farthestCoordinate()
Literal farthestCoordinate (Literal a, Literal b)
Retrieves the farthest coordinate on a geometry to a given point.
Parameters
a The given point
b The geometry to calculaet the farthest coordinate on.
Returns
The farthest coordinate a a geometry lof the same type and CRS as the first input geometry
def farthestCoordinate(a: Literal, b: Literal) -> Literal:
    print("FARTHEST COORDINATE")
    geoms = list(zip(*LiteralUtils.processLiteralsToGeom([a, b], normalize=True)))[0]
    if geoms[0] is not None and geoms[0].geom_type!="Point":
        raise ValueError("The first parameter of the function geof:farthestCoordinate should represent a point geometry")
    print(geoms[0])
    if geoms[0].has_z and geoms[1].has_z:
        clist = shapely.get_coordinates(geoms[1], include_z=True).tolist()
    else:
        clist = shapely.get_coordinates(geoms[1], include_z=False).tolist()
    maxdistance=float("-inf")
    farthest=None
    for p in clist:
        cp=shapely.geometry.Point(p)
        dist=shapely.distance(geoms[0],cp)
        if dist>maxdistance:
            maxdistance=dist
            farthest=cp
    if farthest is not None:
        return LiteralUtils.processGeomToLiteral(farthest,a.datatype,"")
flipXY()
Literal flipXY (Literal a)
Flips the XY coordinates included in the given geometry.
Parameters
a The geometry literal
Returns
The geometry with XY flipped as a geometry literal of the same type and CRS as the input geometry
def flipXY(a: Literal) -> Literal:
    thegeom, thegeomsrs = LiteralUtils.processLiteralTypeToGeom(a)
    return LiteralUtils.processGeomToLiteral(shapely.ops.transform(lambda x, y: (y, x),thegeom), a.datatype, thegeomsrs)
force2D()
Literal force2D (Literal a)
Removes Z coordinates from the given geometry to make it twodimensional.
Parameters
a The geometry literal
Returns
The geometry with Z coordinate removed as a geometry literal of the same type and CRS as the input geometry
def force2D(a: Literal) -> Literal:
    thegeom, thegeomsrs = LiteralUtils.processLiteralTypeToGeom(a)
    return LiteralUtils.processGeomToLiteral(shapely.force_2d(thegeom), a.datatype, thegeomsrs)
forceCCW()
Literal forceCCW (Literal a)
Sets a counterclockwise ring orientation on the exterior ring of a polygon.
Interior rings will be set to a clockwise orientation.
Parameters
a The geometry literal
Returns
The oriented polygon as a geometry literal in the CRS and literal format of the first input geometry
def forceCCW(a: Literal) -> Literal:
    thegeom, thegeomsrs = a.value
    return Literal(shapely.orient_polygons(thegeom,exterior_cw=True), datatype=XSD.boolean)
forceCW()
Literal forceCW (Literal a)
Sets a clockwise ring orientation on the exterior ring of a polygon.
Interior rings will be set to a counterclockwise orientation.
Parameters
a The geometry literal
Returns
The oriented polygon as a geometry literal in the CRS and literal format of the first input geometry
def forceCW(a: Literal) -> Literal:
    thegeom, thegeomsrs = a.value
    return Literal(shapely.orient_polygons(thegeom,exterior_cw=False), datatype=XSD.boolean)
frechetDistance()
Literal frechetDistance (Literal a, Literal b)
Calculates the FrechetDistance between two input geometries.
Parameters
a The first geometry literal
b The second geometry literal
Returns
The frechet distance as a xsd:double Literal
def frechetDistance(a: Literal, b: Literal) -> Literal:
    geoms = list(zip(*LiteralUtils.processLiteralsToGeom([a, b], normalize=True)))[0]
    if geoms[0] is not None and geoms[1] is not None:
        return Literal(shapely.frechet_distance(geoms[0], geoms[1]), datatype=XSD.double)
geometryN()
Literal geometryN (Literal a, Literal n)
Implements geof:geometryN: Returns the nth geometry of a GeometryCollection if it exists.
Parameters
a The geometry literal
n The index of the GeometryCollection to retrieve
Returns
The geometry at the nth position of the given GeometryColleciton as a geometry literal of the same type and CRS as the input geometry
def geometryN(a: Literal, n: Literal) -> Literal:
    if isinstance(a, Literal) and isinstance(n, Literal) and n.datatype == XSD.integer:
        thegeom, thegeomsrs = LiteralUtils.processLiteralTypeToGeom(a)
        print(thegeom)
        print(shapely.get_geometry(thegeom, int(str(n))))
        return LiteralUtils.processGeomToLiteral(shapely.get_geometry(thegeom, int(str(n))), a.datatype, thegeomsrs)
geometryType()
Literal geometryType (Literal a)
Implements geof:geometryType: Retrieves the geometry type of a geometry literal.
Parameters
a The geometry literal
Returns
The geometry type as a xsd:string Literal
def geometryType(a: Literal) -> Literal:
    thegeom, thegeomsrs = LiteralUtils.processLiteralTypeToGeom(a)
    return Literal(thegeom.geom_type, datatype=XSD.string)
getfuncs()
getfuncs ()
def getfuncs():
    thefuncs = merge_dicts(geosparql10, geosparql11, geosparql13)
    print("")
    for uri in thefuncs:
        try:
            register_custom_function(uri, thefuncs[uri])
            print("Registered custom function", uri)
            # print(thefuncs[uri])
        except ValueError:
            pass
        except AttributeError:
            pass
    #term.bind(URIRef(str(GEO)+"wktLiteral"),shapely.Geometry,LiteralUtils.processWKTLiteral,LiteralUtils.processGeomToWKTLiteral)
    #term.bind(URIRef(str(GEO) + "gmlLiteral"), shapely.Geometry, LiteralUtils.processGMLLiteral,LiteralUtils.processGeomToGMLLiteral)
    #term.bind(URIRef(str(GEO) + "kmlLiteral"), shapely.Geometry, LiteralUtils.processKMLLiteral,LiteralUtils.processGeomToKMLLiteral)
    #term.bind(URIRef(str(GEO) + "geoJSONLiteral"), shapely.Geometry, LiteralUtils.processGeoJSONLiteral,LiteralUtils.processGeomToGeoJSONLiteral)
References geosparql.geosparql.getfuncs(), and geosparql.geosparql.merge_dicts().
Referenced by geosparql.geosparql.getfuncs().
getSRID()
Literal getSRID (Literal a)
Implements geof:getSRID: Retrieves the SRID URI of a geometry.
Parameters
a The geometry literal
Returns
The srid URI as a xsd:anyURI Literal
def getSRID(a: Literal) -> Literal:
    thegeom, thegeomsrs = LiteralUtils.processLiteralTypeToGeom(a)
    return Literal(thegeomsrs, datatype=XSD.anyURI)
hausdorffDistance()
Literal hausdorffDistance (Literal a, Literal b)
Calculates the HausdorffDistance between two input geometries.
Parameters
a The first geometry literal
b The second geometry literal
Returns
The hausdorff distance as a xsd:double Literal
def hausdorffDistance(a: Literal, b: Literal) -> Literal:
    geoms = list(zip(*LiteralUtils.processLiteralsToGeom([a, b], normalize=True)))[0]
    if geoms[0] is not None and geoms[1] is not None:
        return Literal(shapely.hausdorff_distance(geoms[0], geoms[1]), datatype=XSD.double)
inside()
Literal inside (Literal a, Literal b)
Implements geof:ehInside geof:rcc8ntpp: Calculates whether the first geometry is inside the second geometry.
Parameters
a The first geometry literal
b The second geometry literal
Returns
A xsd:boolean Literal indicating whether the first geometry is inside the second geometry
def inside(a: Literal, b: Literal) -> Literal:
    geoms = list(zip(*LiteralUtils.processLiteralsToGeom([a, b], normalize=True)))[0]
    if geoms[0] is not None and geoms[1] is not None:
        print(shapely.contains_properly(geoms[1], geoms[0]))
        return Literal(shapely.contains_properly(geoms[1], geoms[0]), datatype=XSD.boolean)
interpolatePoint()
Literal interpolatePoint (Literal a, Literal d)
Returns a point interpolated at a given distance on a line.
Parameters
a The geometry literal
d The distance
Returns
The interpolated point
def interpolatePoint(a: Literal, d: Literal) -> Literal:
    thegeom, thegeomsrs = LiteralUtils.processLiteralTypeToGeom(a)
    return LiteralUtils.processGeomToLiteral(shapely.line_interpolate_point(thegeom,float(str(d.value))), a.datatype)
intersection()
Literal intersection (Literal a, Literal b)
Implements geof:intersection: Calculates the intersection of two geometry literals.
Parameters
a The first geometry literal
b The second geometry literal
Returns
The intersection as a geometry literal in the CRS and literal format of the first input geometry
def intersection(a: Literal, b: Literal) -> Literal:
    geomtps = LiteralUtils.processLiteralsToGeom([a, b], normalize=True)
    if len(geomtps) > 1:
        return LiteralUtils.processGeomToLiteral(shapely.intersection(geomtps[0][0], geomtps[1][0]), a.datatype,geomtps[0][1])
Referenced by geosparql.geosparql.intersection3D().
intersection3D()
Literal intersection3D (Literal a, Literal b)
def intersection3D(a: Literal, b: Literal) -> Literal:
    geoms = list(zip(*LiteralUtils.processLiteralsToGeom([a, b], normalize=True, create3D=True)))[0]
    print(geoms)
    print(geoms[0].intersection(geoms[1]))
    print(geoms[0].intersection(geoms[1]).volume)
    if geoms[0] is not None and geoms[1] is not None:
        return Literal(str(geoms[0].intersection(geoms[1])), datatype=XSD.string)
References geosparql.geosparql.intersection().
intersects()
Literal intersects (Literal a, Literal b)
Implements geof:sfIntersects: Calculates whether the two input geometries intersect.
Parameters
a The first geometry literal
b The second geometry literal
Returns
A xsd:boolean Literal indicating whether the two geometries intersect
def intersects(a: Literal, b: Literal) -> Literal:
    geoms = list(zip(*LiteralUtils.processLiteralsToGeom([a, b], normalize=True)))[0]
    if geoms[0] is not None and geoms[1] is not None:
        return Literal(shapely.intersects(geoms[0], geoms[1]), datatype=XSD.boolean)
intersects3D()
Literal intersects3D (Literal a, Literal b)
def intersects3D(a: Literal, b: Literal) -> Literal:
    geoms = list(zip(*LiteralUtils.processLiteralsToGeom([a, b], normalize=True, create3D=True)))[0]
    if geoms[0] is not None and geoms[1] is not None:
        print(trimesh.boolean.boolean_manifold(geoms, "intersection"))
        return Literal(trimesh.boolean.boolean_manifold(geoms, "intersection").volume>0, datatype=XSD.boolean)
is3D()
Literal is3D (Literal a)
Implements geof:is3D: Calculates whether a geometry literal represents a 3D geometry.
Parameters
a The geometry literal
Returns
A xsd:boolean Literal indicating whether the geometry is threedimensional
def is3D(a: Literal) -> Literal:
    thegeom, thegeomsrs = a.value
    return Literal(thegeom.has_z, datatype=XSD.boolean)
isCCW()
Literal isCCW (Literal a)
Checks whether the coordinates of a LineString or LinearRing are counterclockwise.
Parameters
a The geometry literal
Returns
A xsd:boolean Literal indicating whether the LineString or LinearRing is counterclockwise
def isCCW(a: Literal) -> Literal:
    thegeom, thegeomsrs = a.value
    return Literal(shapely.is_ccw(thegeom), datatype=XSD.boolean)
isClosed()
Literal isClosed (Literal a)
Implements geof:isClosed: Calculates whether a geometry literal represents a closed geometry.
Parameters
a The geometry literal
Returns
A xsd:boolean Literal indicating whether the geometry is closed
def isClosed(a: Literal) -> Literal:
    thegeom, thegeomsrs = LiteralUtils.processLiteralTypeToGeom(a)
    if "Polygon" in thegeom.geom_type:
        return Literal(True, datatype=XSD.boolean)
    return Literal(thegeom.is_closed, datatype=XSD.boolean)
isCollection()
Literal isCollection (Literal a)
Indicates whether a geometry literal contains a GeometryCollection.
Parameters
a The geometry literal
Returns
A xsd:boolean Literal indicating whether the geometry is a GeometryCollection
def isCollection(a: Literal) -> Literal:
    thegeom, thegeomsrs = LiteralUtils.processLiteralTypeToGeom(a)
    return Literal(str(thegeom.geom_type) == "GeometryCollection" or str(thegeom.geom_type).startswith("Multi"),
                   datatype=XSD.boolean)
isEmpty()
Literal isEmpty (Literal a)
Implements geof:isEmpty: Calculates whether a geometry literal represents a closed geometry.
Parameters
a The geometry literal
Returns
A xsd:boolean Literal indicating whether the geometry is closed
def isEmpty(a: Literal) -> Literal:
    thegeom, thegeomsrs = LiteralUtils.processLiteralTypeToGeom(a)
    print(thegeom)
    print(shapely.is_empty(thegeom))
    return Literal(shapely.is_empty(thegeom), datatype=XSD.boolean)
isMeasured()
Literal isMeasured (Literal a)
Implements geof:isMeasured: Calculates whether a geometry literal has measurement coordinates.
Parameters
a The geometry literal
Returns
A xsd:boolean Literal indicating whether the geometry has measurement coordinates
def isMeasured(a: Literal) -> Literal:
    thegeom, thegeomsrs = LiteralUtils.processLiteralTypeToGeom(a)
    return Literal(thegeom.has_m, datatype=XSD.boolean)
isRectangle()
Literal isRectangle (Literal a)
Calculates whether a geometry literal represents a rectangle.
Parameters
a The geometry literal
Returns
A xsd:boolean Literal indicating whether the geometry is a rectangle
def isRectangle(a: Literal) -> Literal:
    thegeom, thegeomsrs = LiteralUtils.processLiteralTypeToGeom(a)
    if "Polygon" in str(thegeom.geom_type):
        return Literal(math.isclose(thegeom.minimum_rotated_rectangle.area, thegeom.area),datatype=XSD.boolean)
    return Literal(False, datatype=XSD.boolean)
isRing()
Literal isRing (Literal a)
Implements geof:isRing: Calculates whether a geometry literal is a ring.
Parameters
a The geometry literal
Returns
A xsd:boolean Literal indicating whether the geometry is a ring
def isRing(a: Literal) -> Literal:
    thegeom, thegeomsrs = LiteralUtils.processLiteralTypeToGeom(a)
    if "Polygon" in str(thegeom.geom_type):
        return Literal(True, datatype=XSD.boolean)
    return Literal(thegeom.is_ring, datatype=XSD.boolean)
isSimple()
Literal isSimple (Literal a)
Implements geof:isSimple: Calculates whether a geometry literal represents a simple geometry.
Parameters
a The geometry literal
Returns
A xsd:boolean Literal indicating whether the geometry is simple
def isSimple(a: Literal) -> Literal:
    thegeom, thegeomsrs = LiteralUtils.processLiteralTypeToGeom(a)
    print(thegeom.is_simple)
    print("The Lit: " + str(Literal(thegeom.is_simple, datatype=XSD.boolean)))
    return Literal(thegeom.is_simple, datatype=XSD.boolean)
isTriangle()
Literal isTriangle (Literal a)
Calculates whether a geometry is a triangle.
Parameters
a The geometry literal
Returns
A xsd:boolean Literal whether the geometry is a triangle
def isTriangle(a: Literal) -> Literal:
    thegeom, thegeomsrs = LiteralUtils.processLiteralTypeToGeom(a)
    if thegeom.geom_type=="Triangle" or (thegeom.geom_type=="Polygon" and shapely.count_coordinates(thegeom)==4):
        return Literal(True, datatype=XSD.boolean)
    return Literal(False, datatype=XSD.boolean)
isValid()
Literal isValid (Literal a)
Calculates whether a geometry literal represents a valid geometry.
Parameters
a The geometry literal
Returns
A xsd:boolean Literal indicating whether the geometry is valid
def isValid(a: Literal) -> Literal:
    thegeom, thegeomsrs = LiteralUtils.processLiteralTypeToGeom(a)
    return Literal(thegeom.is_valid, datatype=XSD.boolean)
isValidTrajectory()
Literal isValidTrajectory (Literal a)
Calculates whether a geometry literal encodes a valid trajectory.
Parameters
a The geometry literal
Returns
A xsd:boolean Literal indicating whether the geometry encodes a valid trajectory
def isValidTrajectory(a: Literal) -> Literal:
    thegeom, thegeomsrs = LiteralUtils.processLiteralTypeToGeom(a)
    if thegeom.geom_type=="LineString" and shapely.has_m(thegeom):
        clist = shapely.get_coordinates(thegeom, include_m=True).tolist()
        curM=-float("inf")
        print(clist)
        for c in clist:
            print("curM: " + str(curM))
            if curM>c[2]:
                return Literal(False, datatype=XSD.boolean)
            curM = c[2]
        return Literal(True, datatype=XSD.boolean)
    return Literal(False, datatype=XSD.boolean)
leftOf()
Literal leftOf (Literal a, Literal b)
Calculates whether the first geometry is left of the second geometry.
Parameters
a The first geometry literal
b The second geometry literal
Returns
A xsd:boolean Literal indicating whether the first geometry is left of the second geometry
def leftOf(a: Literal, b: Literal) -> Literal:
    geoms = list(zip(*LiteralUtils.processLiteralsToGeom([a, b], normalize=True)))[0]
    if geoms[0] is not None and geoms[1] is not None:
        #geom[0].maxX<geom[1].minX
        geom1bounds=shapely.total_bounds(geoms[0])
        geom2bounds=shapely.total_bounds(geoms[1])
        ro=range_overlap(geom1bounds[1],geom1bounds[3],geom2bounds[1],geom2bounds[3])
        return Literal(ro>0 and shapely.total_bounds(geoms[0])[2]<shapely.total_bounds(geoms[1])[0], datatype=XSD.boolean)
References geosparql.geosparql.range_overlap().
length()
Literal length (Literal a, Literal unit)
Implements geof:length: Retrieves the length of a geometry.
Parameters
a The geometry literal
units The unit of measurement of the length as a URI
Returns
The length as a xsd:double Literal
def length(a: Literal,unit: Literal) -> Literal:
    if unit.value not in SRSUtils.uniturisToUnit:
        raise ValueError("The provided unit "+str(unit)+" is not a supported unit.\nSupported units: "+str(SRSUtils.uniturisToUnit.keys()))
    thegeom, thegeomsrs = LiteralUtils.processLiteralTypeToGeom(a)
    normgeom = Transformers.transformToSRS(thegeom, thegeomsrs, 3857)
    thelength=normgeom.length
    if SRSUtils.uniturisToUnit[unit.value]!="meter":
        thelength=SRSUtils.convertMetricToUnit(thelength,"http://qudt.org/vocab/unit/M",unit.value)
    return Literal(thelength, datatype=XSD.double)
longestLine()
Literal longestLine (Literal a, Literal b)
Retrieves the longest line between two geometries defined by the two points with maximum distance.
Parameters
a The first geometry literal.
b The first geometry literal.
Returns
The longest line as a geometry literal in the CRS and literal format of the first input geometry
def longestLine(a: Literal, b: Literal) -> Literal:
    print("LONGESTLINE")
    geoms = list(zip(*LiteralUtils.processLiteralsToGeom([a, b], normalize=True)))[0]
    if geoms[0].has_z and geoms[1].has_z:
        g1list = shapely.get_coordinates(geoms[0], include_z=True).tolist()
        g2list = shapely.get_coordinates(geoms[1], include_z=True).tolist()
    else:
        g1list = shapely.get_coordinates(geoms[0], include_z=False).tolist()
        g2list = shapely.get_coordinates(geoms[1], include_z=False).tolist()
    maxdistance=float("-inf")
    fpoint1=None
    fpoint2=None
    for p1 in g1list:
        for p2 in g2list:
            dist = shapely.distance(shapely.geometry.Point(p1), shapely.geometry.Point(p2))
            print(dist)
            if dist>maxdistance:
                maxdistance=dist
                fpoint1=p1
                fpoint2=p2
    if fpoint1 is not None and fpoint2 is not None:
        return LiteralUtils.processGeomToLiteral(shapely.geometry.LineString([fpoint1,fpoint2]),a.datatype)
m()
Literal m (Literal a)
Retrieves the M coordinate of a Point geometry.
Parameters
a The geometry literal.
Returns
The M coordinate as a xsd:double Literal
def m(a: Literal) -> Literal:
    thegeom, thegeomsrs = LiteralUtils.processLiteralTypeToGeom(a)
    if thegeom.geom_type == "Point":
        return Literal(shapely.get_m(thegeom), datatype=XSD.double)
makeValid()
Literal makeValid (Literal a)
Creates a valid version of an invalid geometry.
Parameters
a The geometry literal
Returns
A valid version of the given input geometry in the CRS and literal format of the first input geometry
def makeValid(a: Literal) -> Literal:
    thegeom, thegeomsrs = LiteralUtils.processLiteralTypeToGeom(a)
    return LiteralUtils.processGeomToLiteral(shapely.make_valid(thegeom), a.datatype)
matrixTransform()
Literal matrixTransform (Literal a, matrix)
def matrixTransform(a: Literal, matrix) -> Literal:
    thegeom, thegeomsrs = LiteralUtils.processLiteralTypeToGeom(a)
    shapely.affinity.affine_transform(thegeom, [])
    if thegeom.geom_type == "Point":
        return Literal(shapely.get_m(thegeom), datatype=XSD.double)
maxDistance()
Literal maxDistance (Literal a, Literal b)
Retrieves the maximum distance between two geometries.
Parameters
a The first geometry literal.
b The first geometry literal.
Returns
The maximum distance as a xsd:double Literal
def maxDistance(a: Literal, b: Literal) -> Literal:
    geoms = list(zip(*LiteralUtils.processLiteralsToGeom([a, b], normalize=True)))[0]
    if geoms[0].has_z and geoms[1].has_z:
        g1list = shapely.get_coordinates(geoms[0], include_z=True).tolist()
        g2list = shapely.get_coordinates(geoms[1], include_z=True).tolist()
    else:
        g1list = shapely.get_coordinates(geoms[0], include_z=False).tolist()
        g2list = shapely.get_coordinates(geoms[1], include_z=False).tolist()
    maxdistance=float("-inf")
    for p1 in g1list:
        for p2 in g2list:
            dist=shapely.distance(shapely.geometry.Point(p1),shapely.geometry.Point(p2))
            if dist>maxdistance:
                maxdistance=dist
    return Literal(str(maxdistance), datatype=XSD.double)
maxM()
Literal maxM (Literal a)
Retrieves the maximum measurement coordinate of a geometry.
Parameters
a The geometry literal.
Returns
The maximum measurement coordinate as a xsd:double Literal
def maxM(a: Literal) -> Literal:
    thegeom, thegeomsrs = LiteralUtils.processLiteralTypeToGeom(a)
    clist = shapely.get_coordinates(thegeom, include_m=True).tolist()
    flinf = -float("inf")
    maxM = flinf
    for c in clist:
        if c[2] != nan and maxM < c[2]:
            maxM = c[2]
    if maxM == flinf:
        maxM = "NaN"
    return Literal(str(maxM), datatype=XSD.double)
maxX()
Literal maxX (Literal a)
Implements geof:maxX: Retrieves the maximum x coordinate of a geometry.
Parameters
a The geometry literal.
Returns
The maximum X coordinate as a xsd:double Literal
def maxX(a: Literal) -> Literal:
    thegeom, thegeomsrs = LiteralUtils.processLiteralTypeToGeom(a)
    return Literal(shapely.total_bounds(thegeom)[2], datatype=XSD.double)
maxY()
Literal maxY (Literal a)
Implements geof:maxY: Retrieves the maximum y coordinate of a geometry.
Parameters
a The geometry literal.
Returns
The maximum Y coordinate as a xsd:double Literal
def maxY(a: Literal) -> Literal:
    thegeom, thegeomsrs = LiteralUtils.processLiteralTypeToGeom(a)
    return Literal(shapely.total_bounds(thegeom)[3], datatype=XSD.double)
maxZ()
Literal maxZ (Literal a)
Implements geof:maxZ: Retrieves the maximum z coordinate of a geometry.
Parameters
a The geometry literal.
Returns
The maximum Z coordinate as a xsd:double Literal
def maxZ(a: Literal) -> Literal:
    thegeom, thegeomsrs = LiteralUtils.processLiteralTypeToGeom(a)
    return Literal(str(Handling3D.maxZ(thegeom)), datatype=XSD.double)
merge_dicts()
merge_dicts (* dict_args)
Given any number of dictionaries, shallow copy and merge into a new dict,
precedence goes to key-value pairs in latter dictionaries.
def merge_dicts(*dict_args):
    """
    Given any number of dictionaries, shallow copy and merge into a new dict,
    precedence goes to key-value pairs in latter dictionaries.
    """
    result = {}
    for dictionary in dict_args:
        result.update(dictionary)
    return result
Referenced by geosparql.geosparql.getfuncs().
metricArea()
Literal metricArea (Literal a)
Implements geof:metricArea: Calculates the area of a 2D geometry provided as a geometry literal in squaremeters.
Parameters
a The geometry literal.
Returns
The area in squaremeters as an xsd:double Literal
def metricArea(a: Literal) -> Literal:
    thegeom, thegeomsrs = LiteralUtils.processLiteralTypeToGeom(a)
    normgeom = Transformers.transformToSRS(thegeom, thegeomsrs, 3857)
    return Literal(shapely.area(normgeom), datatype=XSD.double)
metricBuffer()
Literal metricBuffer (Literal a, Literal radius)
Implements geof:metricBuffer: Calculates a buffer of a 2D geometry from a given radius.
Parameters
a The geometry literal.
radius The radius of the buffer to create.
Returns
The buffer as a geometry Literal
def metricBuffer(a: Literal, radius: Literal) -> Literal:
    thegeom, thegeomsrs = LiteralUtils.processLiteralTypeToGeom(a)
    normgeom = Transformers.transformToSRS(thegeom, thegeomsrs, 3857)
    if isinstance(radius, Literal) and radius.datatype == XSD.double:
        return LiteralUtils.processGeomToLiteral(shapely.buffer(normgeom, float(radius)), a.datatype, thegeomsrs)
metricDistance()
Literal metricDistance (Literal a, Literal b)
Implements geof:metricDistance: Retrieves the distance between two geometries in meters.
Parameters
a The first geometry literal
b The second geometry literal
Returns
The distance in meters as a xsd:double Literal
def metricDistance(a: Literal, b: Literal) -> Literal:
    geoms = list(zip(*LiteralUtils.processLiteralsToGeom([a, b], normalize=True, normsrs=3857)))[0]
    if geoms[0] is not None and geoms[1] is not None:
        return Literal(shapely.distance(geoms[0], geoms[1]), datatype=XSD.double)
metricLength()
Literal metricLength (Literal a)
Implements geof:metricLength: Retrieves the length of a geometry in meters.
Parameters
a The geometry literal
Returns
The length in meters as a xsd:double Literal
def metricLength(a: Literal) -> Literal:
    thegeom, thegeomsrs = LiteralUtils.processLiteralTypeToGeom(a)
    normgeom = Transformers.transformToSRS(thegeom, thegeomsrs, 3857)
    return Literal(shapely.length(normgeom), datatype=XSD.double)
metricPerimeter()
Literal metricPerimeter (Literal a)
Implements geof:metricPerimeter: Retrieves the perimeter length of a geometry in meters.
Parameters
a The geometry literal
Returns
The perimeter length in meters as a xsd:double Literal
def metricPerimeter(a: Literal) -> Literal:
    thegeom, thegeomsrs = LiteralUtils.processLiteralTypeToGeom(a)
    normgeom = Transformers.transformToSRS(thegeom, thegeomsrs, 3857)
    return Literal(normgeom.length, datatype=XSD.double)
metricWithinDistance()
Literal metricWithinDistance (Literal a, b, d)
Calculates whether the first geometry is within a given distance to the second geometry.
The distance is interpreted as meters.
Parameters
a The first geometry literal
b The second geometry literal
d The distance in meters
Returns
A xsd:boolean Literal indicating whether the first geometry is within distance of the second geometry
def metricWithinDistance(a: Literal, b, d) -> Literal:
    geoms = list(zip(*LiteralUtils.processLiteralsToGeom([a, b], normalize=True, normsrs=3857)))[0]
    if isinstance(d, Literal) and d.datatype == XSD.double:
        distance = float(str(d))
        return Literal(shapely.dwithin(geoms[0], geoms[1], distance), datatype=XSD.boolean)
minimumBoundingRadius()
Literal minimumBoundingRadius (Literal a)
Calculates the radius of the minimum bounding circle around the input geometry.
Parameters
a The geometry literal.
Returns
The minimum bounding radius as xsd:double Literal
def minimumBoundingRadius(a: Literal) -> Literal:
    thegeom, thegeomsrs = LiteralUtils.processLiteralTypeToGeom(a)
    return Literal(shapely.minimum_bounding_radius(thegeom), datatype=XSD.double)
minimumClearance()
Literal minimumClearance (Literal a)
Calculates the minimum clearance of the input geometry.
Parameters
a The geometry literal.
Returns
The minimum clearance as xsd:double Literal
def minimumClearance(a: Literal) -> Literal:
    thegeom, thegeomsrs = LiteralUtils.processLiteralTypeToGeom(a)
    return Literal(shapely.minimum_clearance(thegeom), datatype=XSD.double)
minimumClearanceLine()
Literal minimumClearanceLine (Literal a)
Retrieves the minimum clearance line of a geometry.
Parameters
a The first geometry literal.
Returns
The minimum clearance line as a geometry literal in the CRS and literal format of the first input geometry
def minimumClearanceLine(a: Literal) -> Literal:
    thegeom, thegeomsrs = LiteralUtils.processLiteralTypeToGeom(a)
    # print(shapely.minimum_clearance_line(thegeom))
    return LiteralUtils.processGeomToLiteral(shapely.minimum_clearance_line(thegeom), a.datatype)
minM()
Literal minM (Literal a)
Retrieves the minimum measurement coordinate of a geometry.
Parameters
a The geometry literal.
Returns
The minimum measurement coordinate as a xsd:double Literal
def minM(a: Literal) -> Literal:
    thegeom, thegeomsrs = LiteralUtils.processLiteralTypeToGeom(a)
    clist = shapely.get_coordinates(thegeom, include_m=True).tolist()
    flinf = float("inf")
    minM = flinf
    for c in clist:
        if c[2] != nan and minM > c[2]:
            minM = c[2]
    if minM == flinf:
        minM = "NaN"
    return Literal(str(minM), datatype=XSD.double)
minX()
Literal minX (Literal a)
Implements geof:minX: Retrieves the minimum X coordinate of a geometry.
Parameters
a The geometry literal.
Returns
The minimum X coordinate as a xsd:double Literal
def minX(a: Literal) -> Literal:
    thegeom, thegeomsrs = LiteralUtils.processLiteralTypeToGeom(a)
    return Literal(shapely.total_bounds(thegeom)[0], datatype=XSD.double)
minY()
Literal minY (Literal a)
Implements geof:minY: Retrieves the minimum Y coordinate of a geometry.
Parameters
a The geometry literal.
Returns
The minimum Y coordinate as a xsd:double Literal
def minY(a: Literal) -> Literal:
    thegeom, thegeomsrs = LiteralUtils.processLiteralTypeToGeom(a)
    return Literal(shapely.total_bounds(thegeom)[1], datatype=XSD.double)
minZ()
Literal minZ (Literal a)
Implements geof:minZ: Retrieves the minimum z coordinate of a geometry.
Parameters
a The geometry literal.
Returns
The minimum z coordinate as a xsd:double Literal
def minZ(a: Literal) -> Literal:
    thegeom, thegeomsrs = LiteralUtils.processLiteralTypeToGeom(a)
    return Literal(str(Handling3D.minZ(thegeom)), datatype=XSD.double)
numGeometries()
Literal numGeometries (Literal a)
Implements geof:numGeometries: Calculates the number of geometries included in the geometry literal.
Parameters
a The first geometry literal
Returns
A xsd:integer Literal indicating the number of geometries included
def numGeometries(a: Literal) -> Literal:
    thegeom, thegeomsrs = LiteralUtils.processLiteralTypeToGeom(a)
    return Literal(shapely.get_num_geometries(thegeom), datatype=XSD.integer)
numInteriorRing()
Literal numInteriorRing (Literal a)
Implements geof:numInteriorRing: Calculates the number of interior rings included in the geometry literal.
Parameters
a The first geometry literal
Returns
A xsd:integer Literal indicating the number of interior rings
def numInteriorRing(a: Literal) -> Literal:
    thegeom, thegeomsrs = LiteralUtils.processLiteralTypeToGeom(a)
    return Literal(shapely.get_num_interior_rings(thegeom), datatype=XSD.integer)
numPatches()
Literal numPatches (Literal a)
Implements geof:numPatches: Calculates the number of patches included in the geometry literal.
Parameters
a The first geometry literal
Returns
A xsd:integer Literal indicating the number of patches
def numPatches(a: Literal) -> Literal:
    thegeom, thegeomsrs = LiteralUtils.processLiteralTypeToGeom(a)
    return Literal(len(shapely.get_parts(thegeom)), datatype=XSD.integer)
numPoints()
Literal numPoints (Literal a)
Implements geof:numPoints: Calculates the number of points included in the geometry literal.
Parameters
a The first geometry literal
Returns
A xsd:integer Literal indicating the number of points
def numPoints(a: Literal) -> Literal:
    thegeom, thegeomsrs = LiteralUtils.processLiteralTypeToGeom(a)
    return Literal(shapely.count_coordinates(thegeom), datatype=XSD.integer)
offsetCurve()
Literal offsetCurve (Literal a, Literal d)
Creates an offset line at a given distance and side from an input geometry .
Parameters
a The geometry literal
d The distance
Returns
The offset curve as a LineString in the CRS and literal format of the input geometry
def offsetCurve(a: Literal,d: Literal) -> Literal:
    thegeom, thegeomsrs = LiteralUtils.processLiteralTypeToGeom(a)
    return LiteralUtils.processGeomToLiteral(shapely.offset_curve(thegeom,float(str(d))), a.datatype)
overlaps()
Literal overlaps (Literal a, Literal b)
Implements geof:sfOverlaps geof:ehOverlap geof:rcc8po: Calculates whether the two input geometries overlap.
Parameters
a The first geometry literal
b The second geometry literal
Returns
A xsd:boolean Literal indicating whether the two geometries overlap
def overlaps(a: Literal, b: Literal) -> Literal:
    geoms = list(zip(*LiteralUtils.processLiteralsToGeom([a, b], normalize=True)))[0]
    if geoms[0] is not None and geoms[1] is not None:
        return Literal(shapely.overlaps(geoms[0], geoms[1]), datatype=XSD.boolean)
patchN()
Literal patchN (Literal a, Literal n)
Implements geof:patchN: Returns the nth patch of a geometry.
Parameters
a The geometry literal
n The index of the patch to retrieve
Returns
The point at the nth patch of the given geometry as a geometry literal of the same type and CRS as the input geometry
def patchN(a: Literal, n: Literal) -> Literal:
    thegeom, thegeomsrs = LiteralUtils.processLiteralTypeToGeom(a)
    return LiteralUtils.processGeomToLiteral(shapely.get_parts(thegeom).tolist()[n], a.datatype)
perimeter()
Literal perimeter (Literal a, Literal unit)
Implements geof:perimeter: Retrieves the perimeter length of a geometry.
Parameters
a The geometry literal
units The unit of measurement of the length as a URI
Returns
The perimeter length as a xsd:double Literal
def perimeter(a: Literal, unit: Literal) -> Literal:
    if unit.value not in SRSUtils.uniturisToUnit:
        raise ValueError("The provided unit "+str(unit)+" is not a supported unit.\nSupported units: "+str(SRSUtils.uniturisToUnit.keys()))
    thegeom, thegeomsrs = LiteralUtils.processLiteralTypeToGeom(a)
    normgeom = Transformers.transformToSRS(thegeom, thegeomsrs, 3857)
    theperimeter=normgeom.length
    if SRSUtils.uniturisToUnit[unit.value]!="meter":
        theperimeter=SRSUtils.convertMetricToUnit(theperimeter,"http://qudt.org/vocab/unit/M",unit.value)
    return Literal(theperimeter, datatype=XSD.double)
pointN()
Literal pointN (Literal a, n)
Implements geof:pointN: Returns the nth point of a geometry.
Parameters
a The geometry literal
n The index of the point to retrieve
Returns
The point at the nth position of the given geometry as a geometry literal of the same type and CRS as the input geometry
def pointN(a: Literal, n) -> Literal:
    thegeom, thegeomsrs = LiteralUtils.processLiteralTypeToGeom(a)
    if "Polygon" in str(thegeom.geom_type):
        return LiteralUtils.processGeomToLiteral(shapely.get_point(shapely.get_exterior_ring(thegeom), int(str(n))), a.datatype, thegeomsrs)
    return LiteralUtils.processGeomToLiteral(shapely.get_point(thegeom, int(str(n))), a.datatype, thegeomsrs)
pointOnSurface()
Literal pointOnSurface (Literal a)
Returns a point on the surface of the given geometry.
Parameters
a The geometry literal
Returns
The surface point as a geometry literal of the same type and CRS as the input geometry
def pointOnSurface(a: Literal) -> Literal:
    thegeom, thegeomsrs = LiteralUtils.processLiteralTypeToGeom(a)
    print(shapely.point_on_surface(thegeom))
    return LiteralUtils.processGeomToLiteral(shapely.point_on_surface(thegeom), a.datatype, thegeomsrs)
range_overlap()
range_overlap (start1, end1, start2, end2)
how much does the range (start1, end1) overlap with (start2, end2)
def range_overlap(start1, end1, start2, end2):
    """how much does the range (start1, end1) overlap with (start2, end2)"""
    return max(max((end2-start1), 0) - max((end2-end1), 0) - max((start2-start1), 0), 0)
Referenced by geosparql.geosparql.above(), geosparql.geosparql.above3D(), geosparql.geosparql.behind(), geosparql.geosparql.below(), geosparql.geosparql.leftOf(), and geosparql.geosparql.rightOf().
relate()
Literal relate (Literal a, Literal b, Literal matrix)
Implements geof:relate: Calculates whether two input geometries conform to a given DE-9IM pattern.
Parameters
a The first geometry literal
b The second geometry literal
matrix The DE-9IM pattern
Returns
A xsd:boolean Literal indicating whether the two geometries conform with the DE-9IM pattern
def relate(a: Literal, b: Literal, matrix: Literal) -> Literal:
    geoms = list(zip(*LiteralUtils.processLiteralsToGeom([a, b], normalize=True)))[0]
    if geoms[0] is not None and geoms[1] is not None:
        return Literal(shapely.relate_pattern(geoms[0], geoms[1], str(matrix)), datatype=XSD.boolean)
removeRepeatedPoints()
Literal removeRepeatedPoints (Literal a)
Creates a geometry without repeated points.
Parameters
a The geometry literal
Returns
The geometry without repeated points in the CRS and literal format of the input geometry
def removeRepeatedPoints(a: Literal) -> Literal:
    thegeom, thegeomsrs = LiteralUtils.processLiteralTypeToGeom(a)
    return LiteralUtils.processGeomToLiteral(shapely.remove_repeated_points(thegeom), a.datatype)
reverse()
Literal reverse (Literal a)
Returns a version of the input geometry with reversed point order.
Parameters
a The geometry literal
Returns
The reversed geometry in the same literal format and CRS as the input geometry
def reverse(a: Literal) -> Literal:
    thegeom, thegeomsrs = LiteralUtils.processLiteralTypeToGeom(a)
    return LiteralUtils.processGeomToLiteral(shapely.reverse(thegeom), a.datatype, thegeomsrs)
rightOf()
Literal rightOf (Literal a, Literal b)
Calculates whether the first geometry is right of the second geometry.
Parameters
a The first geometry literal
b The second geometry literal
Returns
A xsd:boolean Literal indicating whether the first geometry is right of the second geometry
def rightOf(a: Literal, b: Literal) -> Literal:
    geoms = list(zip(*LiteralUtils.processLiteralsToGeom([a, b], normalize=True)))[0]
    if geoms[0] is not None and geoms[1] is not None:
        #geom[0].minX>geom[1].maxX
        geom1bounds=shapely.total_bounds(geoms[0])
        geom2bounds=shapely.total_bounds(geoms[1])
        ro=range_overlap(geom1bounds[1],geom1bounds[3],geom2bounds[1],geom2bounds[3])
        return Literal(ro>0 and shapely.total_bounds(geoms[0])[0]>shapely.total_bounds(geoms[1])[2], datatype=XSD.boolean)
References geosparql.geosparql.range_overlap().
rotate()
Literal rotate (Literal a, Literal angle)
Implements geof:relate: Calculates whether two input geometries conform to a given DE-9IM pattern.
Parameters
a The first geometry literal
b The rotation angle in degree
Returns
A rotated geometry
def rotate(a: Literal,angle: Literal) -> Literal:
    thegeom, thegeomsrs = LiteralUtils.processLiteralTypeToGeom(a)
    return Literal(shapely.affinity.rotate(thegeom,float(angle.value)), datatype=XSD.boolean)
scale()
Literal scale (Literal a, Literal scaleX, Literal scaleY, Literal scaleZ)
Returns a scaled version of the input geometry.
Parameters
a The geometry literal
scaleX The scale factor in X direction
scaleY The scale factor in Y direction
scaleZ The scale factor in Z direction
Returns
The scaled geometry in the same literal format and CRS as the input geometry
def scale(a: Literal, scaleX: Literal, scaleY: Literal, scaleZ: Literal) -> Literal:
    thegeom, thegeomsrs = LiteralUtils.processLiteralTypeToGeom(a)
    print(shapely.affinity.scale(thegeom, xfact=float(scaleX.value), yfact=float(scaleY.value),
                                 zfact=float(scaleZ.value)))
    return LiteralUtils.processGeomToLiteral(
        shapely.affinity.scale(thegeom, xfact=float(scaleX.value), yfact=float(scaleY.value),
                               zfact=float(scaleZ.value)), a.datatype, thegeomsrs)
shortestLine()
Literal shortestLine (Literal a, Literal b)
Retrieves the shortest line between two geometries defined by the two points with minimum distance.
Parameters
a The first geometry literal.
b The first geometry literal.
Returns
The shortest line as a geometry literal in the CRS and literal format of the first input geometry
def shortestLine(a: Literal, b: Literal) -> Literal:
    geomtps = LiteralUtils.processLiteralsToGeom([a, b], normalize=True)
    print(geomtps)
    print(geomtps[0][0])
    print(geomtps[1][0])
    print(shapely.shortest_line(geomtps[0][0], geomtps[1][0]))
    if len(geomtps) > 1:
        return LiteralUtils.processGeomToLiteral(shapely.shortest_line(geomtps[0][0], geomtps[1][0]), a.datatype,
                                                 geomtps[0][1])
simplify()
Literal simplify (Literal a, Literal tolerance)
Returns a simplfied version of the input geometry calculated with the Douglas Peucker simplification algoritm.
Parameters
a The geometry literal
tolerance a tolerance value
Returns
The simplified geometry in the same literal format and CRS as the input geometry
def simplify(a: Literal, tolerance: Literal) -> Literal:
    thegeom, thegeomsrs = LiteralUtils.processLiteralTypeToGeom(a)
    return LiteralUtils.processGeomToLiteral(shapely.simplify(thegeom, float(tolerance)), a.datatype, thegeomsrs)
skew()
Literal skew (Literal a, Literal xs, Literal ys)
Returns a skewed version of the input geometry.
Parameters
a The geometry literal
xs The skew value in X direction
xy The skew value in Y direction
Returns
The skewed geometry in the same literal format and CRS as the input geometry
def skew(a: Literal, xs: Literal, ys: Literal) -> Literal:
    thegeom, thegeomsrs = LiteralUtils.processLiteralTypeToGeom(a)
    return LiteralUtils.processGeomToLiteral(shapely.affinity.skew(thegeom, xs, ys), a.datatype, thegeomsrs)
spatialDimension()
Literal spatialDimension (Literal a)
Implements geof:spatialDimension: Calculates the spatial dimension of a geometry literal.
Parameters
a The geometry literal
Returns
The spatial dimension as a xsd:integer Literal
def spatialDimension(a: Literal) -> Literal:
    thegeom, thegeomsrs = LiteralUtils.processLiteralTypeToGeom(a)
    return Literal(shapely.get_dimensions(thegeom), datatype=XSD.integer)
startPoint()
Literal startPoint (Literal a)
Extracts the first point of an input geometry.
Parameters
a The geometry literal
Returns
The first point as a geometry literal in the CRS and literal format of the input geometry
def startPoint(a: Literal) -> Literal:
    thegeom, thegeomsrs = LiteralUtils.processLiteralTypeToGeom(a)
    return LiteralUtils.processGeomToLiteral(shapely.Point(shapely.get_coordinates(thegeom)[0]), a.datatype, thegeomsrs)
symDifference()
Literal symDifference (Literal a, Literal b)
Implements geof:symDifference: Calculates the symmetric difference of two geometry literals.
Parameters
a The first geometry literal
b The second geometry literal
Returns
The symmetric difference as a geometry literal in the CRS and literal format of the first input geometry
def symDifference(a: Literal, b: Literal) -> Literal:
    geomtps = LiteralUtils.processLiteralsToGeom([a, b], normalize=True)
    if len(geomtps) > 1:
        return LiteralUtils.processGeomToLiteral(shapely.symmetric_difference(geomtps[0][0], geomtps[1][0]), a.datatype,
                                                 geomtps[0][1])
touches()
Literal touches (Literal a, Literal b)
Implements geof:sfTouches geof:ehMeet geof:rcc8ec: Calculates whether the two input geometries touch.
Parameters
a The first geometry literal
b The second geometry literal
Returns
A xsd:boolean Literal indicating whether the two geometries touch
def touches(a: Literal, b: Literal) -> Literal:
    geoms = list(zip(*LiteralUtils.processLiteralsToGeom([a, b], normalize=True)))[0]
    if geoms[0] is not None and geoms[1] is not None:
        return Literal(shapely.touches(geoms[0], geoms[1]), datatype=XSD.boolean)
    raise ValueError("Invalid parameters were provided for function geof:touches")
transform()
Literal transform (Literal a, Literal srsIRI)
Implements geof:transform: Transforms a given geometry literal to a given CRS.
Parameters
a The geometry literal
srsIRI The IRI identifying the target CRS
Returns
The transformed geometry as a geometry literal in the same literal format as the input geometry
def transform(a: Literal, srsIRI: Literal) -> Literal:
    thegeom, thegeomsrs = LiteralUtils.processLiteralTypeToGeom(a)
    print("TRANSFORM FUNCTION")
    geom=Transformers.transformToSRS(thegeom, thegeomsrs, srsIRI)
    print("GEOM: "+str(geom))
    print("AS LITERAL: "+str(LiteralUtils.processGeomToLiteral(geom, a.datatype,srsIRI)))
    if thegeom is not None and thegeomsrs is not None:
        return LiteralUtils.processGeomToLiteral(Transformers.transformToSRS(thegeom, thegeomsrs, srsIRI), a.datatype,srsIRI)
    raise ValueError("An invalid geometry literal was provided or an illegal transformation requested for function geof:transform")
transformCRS84()
Literal transformCRS84 (Literal a)
Transforms a given geometry literal to the CRS84 CRS.
Parameters
a The geometry literal
Returns
The transformed geometry as a geometry literal in the same literal format as the input geometry
def transformCRS84(a: Literal) -> Literal:
    thegeom, thegeomsrs = LiteralUtils.processLiteralTypeToGeom(a)
    if thegeom is not None and thegeomsrs is not None:
        return LiteralUtils.processGeomToLiteral(Transformers.transformToSRS(thegeom, thegeomsrs, CRS84URI), a.datatype,
                                                 CRS84URI)
    raise ValueError(
        "An invalid geometry literal was provided or an illegal transformation requested for function geof:transformCRS84")
translate()
Literal translate (Literal a, Literal deltaX, Literal deltaY, Literal deltaZ)
Returns a translated version of the input geometry.
Parameters
a The geometry literal
deltaX The translation value in X direction
deltaY The translation value in Y direction
deltaZ The translation value in Z direction
Returns
The translated geometry in the same literal format and CRS as the input geometry
def translate(a: Literal, deltaX: Literal, deltaY: Literal, deltaZ: Literal) -> Literal:
    thegeom, thegeomsrs = LiteralUtils.processLiteralTypeToGeom(a)
    if (isinstance(deltaX, Literal) and deltaX.datatype == XSD.double and isinstance(deltaY,
                                                                                     Literal) and deltaY.datatype == XSD.double and isinstance(
            deltaZ, Literal) and deltaZ.datatype == XSD.double):
        return LiteralUtils.processGeomToLiteral(
            shapely.affinity.translate(thegeom, float(deltaX.value), float(deltaY.value), float(deltaZ.value)),
            a.datatype, thegeomsrs)
    raise ValueError("Invalid parameters were provided for function geof:translate")
union()
Literal union (Literal a, Literal b)
Implements geof:union: Calculates the union of two geometry literals.
Parameters
a The first geometry literal
b The second geometry literal
Returns
The union as a geometry literal in the CRS and literal format of the first input geometry
def union(a: Literal, b: Literal) -> Literal:
    geomtps = LiteralUtils.processLiteralsToGeom([a, b], normalize=True)
    if len(geomtps) > 1:
        return LiteralUtils.processGeomToLiteral(shapely.union(geomtps[0][0], geomtps[1][0]), a.datatype, geomtps[0][1])
    raise ValueError("Invalid parameters were provided for function geof:union")
union3D()
Literal union3D (Literal a, Literal b)
Implements geof:union: Calculates the union of two geometry literals.
Parameters
a The first geometry literal
b The second geometry literal
Returns
The union as a geometry literal in the CRS and literal format of the first input geometry
def union3D(a: Literal, b: Literal) -> Literal:
    geoms = list(zip(*LiteralUtils.processLiteralsToGeom([a, b], normalize=True, create3D=True)))[0]
    if geoms[0] is not None and geoms[1] is not None:
        print(trimesh.boolean.boolean_manifold(geoms, "intersection"))
        return Literal(trimesh.boolean.union(geoms), datatype=XSD.boolean)
within()
Literal within (Literal a, Literal b)
Implements geof:sfWithin: Calculates whether the first geometry is within the second geometry.
Parameters
a The first geometry literal
b The second geometry literal
Returns
A xsd:boolean Literal indicating whether the first geometry is within the second geometry
def within(a: Literal, b: Literal) -> Literal:
    geoms = list(zip(*LiteralUtils.processLiteralsToGeom([a, b], normalize=True)))[0]
    if geoms[0] is not None and geoms[1] is not None:
        return Literal(shapely.within(geoms[0], geoms[1]), datatype=XSD.boolean)
    raise ValueError("Invalid parameters were provided for function geof:within")
withinDistance()
Literal withinDistance (Literal a, Literal b, Literal d, Literal unit)
Calculates whether the first geometry is within a given distance to the second geometry.
Parameters
a The first geometry literal
b The second geometry literal
d The distance
Returns
A xsd:boolean Literal indicating whether the first geometry is within distance of the second geometry
def withinDistance(a: Literal, b: Literal, d: Literal, unit: Literal) -> Literal:
    geoms = list(zip(*LiteralUtils.processLiteralsToGeom([a, b], normalize=True)))[0]
    if isinstance(d, Literal) and d.datatype == XSD.double:
        distance = float(str(d))
        return Literal(str(shapely.dwithin(geoms[0], geoms[1], distance)), datatype=XSD.boolean)
x()
Literal x (Literal a)
Retrieves the X coordinate of a Point geometry.
Parameters
a The geometry literal.
Returns
The X coordinate as a xsd:double Literal
def x(a: Literal) -> Literal:
    thegeom, thegeomsrs = LiteralUtils.processLiteralTypeToGeom(a)
    if thegeom.geom_type == "Point":
        return Literal(shapely.get_x(thegeom), datatype=XSD.double)
    raise ValueError("Invalid parameters, e.g. a non-Point geometry literal was provided for function geof:x")
y()
Literal y (Literal a)
Retrieves the Y coordinate of a Point geometry.
Parameters
a The geometry literal.
Returns
The Y coordinate as a xsd:double Literal
def y(a: Literal) -> Literal:
    thegeom, thegeomsrs = LiteralUtils.processLiteralTypeToGeom(a)
    if thegeom.geom_type == "Point":
        return Literal(shapely.get_y(thegeom), datatype=XSD.double)
    raise ValueError("Invalid parameters, e.g. a non-Point geometry literal was provided for function geof:y")
z()
Literal z (Literal a)
Retrieves the Z coordinate of a Point geometry.
Parameters
a The geometry literal.
Returns
The Z coordinate as a xsd:double Literal
def z(a: Literal) -> Literal:
    thegeom, thegeomsrs = LiteralUtils.processLiteralTypeToGeom(a)
    if thegeom.geom_type == "Point" and thegeom.has_z:
        return Literal(str(shapely.get_z(thegeom)), datatype=XSD.double)
    raise ValueError(
        "Invalid parameters, e.g. a non-Point geometry literal or a non-3D geometry was provided for function geof:z")
Variable Documentation
CRS84URI
str CRS84URI = "http://www.opengis.net/def/crs/OGC/1.3/CRS84"
dir_path
dir_path = os.path.dirname(os.path.realpath(__file__))
g
g = Graph()
GEO
str GEO = "http://www.opengis.net/ont/geosparql#"
GEOF
str GEOF = "http://www.opengis.net/def/function/geosparql/"
GEOFEXT
str GEOFEXT = "http://www.opengis.net/def/function/geosparql/ext/"
GEOFEXTPREFIX
str GEOFEXTPREFIX = "geofext:"
GEOFPREFIX
str GEOFPREFIX = "geof:"
geosparql10
dict geosparql10
geosparql11
dict geosparql11
geosparql13
dict geosparql13
result
result
Initial value:
=  g.query(
    +str(GEO)++str(GEOF)+
)