name: Python CI

on: [push]

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false
 
jobs:

  build:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Create Doxygen Documentation 🔧
      run: |
         sudo apt-get install python3 python3-setuptools python3-pip python3-dev  -y
         sudo apt-get install gcc libpq-dev -y
         sudo apt-get install doxygen graphviz -y
         sudo apt-get install python3-venv python3-wheel -y
         sudo pip3 install wheel pytest pytest-md pytest-emoji
         sudo pip3 install -r requirements.txt
         cd docs
         doxygen Doxyfile
         ls html/
         cd ..
    - name: Setup Pages
      uses: actions/configure-pages@v5
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
          # Upload entire repository
          path: 'docs/html/'
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v5
  
  test:
  
    runs-on: ubuntu-latest

    steps:  
      - name: Install dependencies 🔧
        run: |
           sudo apt-get install python3 python3-setuptools python3-pip python3-dev  -y
           sudo pip3 install wheel pytest pytest-md pytest-emoji
      - name: Run pytest
        uses: pavelzw/pytest-action@v2
        with:
          verbose: true
          emoji: true
          job-summary: true
          custom-arguments: '-q'
          click-to-expand: true
          report-title: 'Test Report'

